### ISSUE TITLE
Add text annotation widget

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#100]
Similar to https://monarchinitiative.org/annotate/text, we should add a simple text annotation feature that provides results that link to data pages as well as the analyze phenotype widget.  This could go on its own page to be added to the home page (or both).

**Comment by pnrobinson** [comment]
Don't understand what this widget is supposed to be doing that goes beyond the current widget?

**Comment by monicacecilia** [comment]
The Monarch widget currently available on the legacy site has not yet been implemented in the new website.

**Comment by kshefchek** [comment]
@iimpulse @pnrobinson are you familiar enough with this service to make a start on it?  If not let me know and I can give a tour.

fyi the code for the original is here: https://github.com/monarch-initiative/monarch-app/blob/master/lib/monarch/web/webapp.js#L2395 but suspect it will be a full rewrite
