### ISSUE TITLE
Add link outs to other Monarch tools that are currently not integrated in the website

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#101]
Add a page with links and descriptions of our external tools for text annotation, curation, exomiser, phenix, etc.

See https://monarchinitiative.org/page/exomes and http://monarchinitiative.org/

**Comment by monicacecilia** [comment]
![Screen Shot 2019-07-09 at 10 07 28 AM](https://user-images.githubusercontent.com/1714621/60908725-6b5f0f80-a231-11e9-94ea-d1a5e1fee02a.png)

**Comment by pnrobinson** [comment]
@monicacecilia Should we have one page for all of these tools? That would make more sense to me than to have one page for exomes and one page for other stuff.

**Comment by monicacecilia** [comment]
I agree. Let's have one page for all the tools. 

@iimpulse Instead of 'Exomes,' let's call this page 'Other resources from the Monarch Initiative,' and let's create a submenu item under the 'Tools' top-level menu that is labeled as 'Other Monarch Tools.'

**Comment by iimpulse** [comment]
@pnrobinson I'll take this.
