### ISSUE TITLE
Add phenogrid to any entity associated with a list of phenotypes

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#104]
We previously had a tab for phenogrid on any entity associated with phenotypes (diseases, genes, variants, etc.)  We should either add phenogrid to the overview section or require clicking on a card/icon to view it.

**Comment by monicacecilia** [comment]
Is this going to absorb #38 (which is in itself leftover from #26)?

**Comment by kshefchek** [comment]
I think both tasks are big enough to be in distinct tickets, and we can lump now with projects.

**Comment by pnrobinson** [comment]
@kshefchek are you going to be doing this issue? If so, please assign yourself. If not, then we need to decide who is responsible for this. I do not understand what exactly the requirement is.

**Comment by kshefchek** [comment]
it's not on my radar but I'm happy to take a pass at it.

There should be some example code on how to create phenogrid given a list of phenotypes from the analyze phenotypes widget.  I can take a look and see how trivial it is to port that to the data pages.

**Comment by kshefchek** [comment]
Given the work Dan and @iimpulse have done on phenogrid, this should be ready to implement.  The code should perform a search on all diseases and genes given phenotypes annotated to an entity.  See the legacy app for how this currently behaves.
