### ISSUE TITLE
Fix display of genotype information

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#108]
When displaying details about genotype, we need to better organize the information to make it easier for the user to parse what is being displayed. 

For example, for the results we offer for genotype MGI:3689705

We should differentiate allelic composition, in this case --> 
```Nf1tm1Fcr/Nf1tm1Par``` and ```Pax3tm1(cre)Joe/Pax3+```

from genetic background, in this case --> ```involves: 129S/SvEv * 129S1/Sv * 129X1/SvJ```

Instead, in https://beta.monarchinitiative.org/genotype/MGI:3689705#gene, all this information is displayed in the header without differentiating the two. As shown here: 
![Screen Shot 2019-07-02 at 12 16 27 PM](https://user-images.githubusercontent.com/1714621/60540146-54656e00-9cc3-11e9-9893-c6136e6a2601.png)

Also, we should be able to display superscript and subscript text as appropriate. In the example above, the actual display of the allelic composition should be as shown below.
![Screen Shot 2019-07-02 at 12 09 33 PM](https://user-images.githubusercontent.com/1714621/60539905-b376b300-9cc2-11e9-8640-72e2c69efe5a.png)

**Comment by pnrobinson** [comment]
@monicacecilia @cmungall It seems to me that this is a backend issue that needs to be solved in biolink rather than by some parsing code in the front end? Can the API return this kind of information? If so it should not be hard to implement. If not, then we should add a blocked by API label.

**Comment by monicacecilia** [comment]
Tagging @kshefchek and @deepakunni3 with a request for comment on whether the API can return this kind of information.

**Comment by kshefchek** [comment]
I think we need source specific rules for replacing characters with superscript tags.  For example, MGI labels use angle brackets to signify superscript, but we wouldn't want the same rule for HGVS labels from ClinVar.  Flybase uses brackets.  This can be done in either biolink or the app code.

Also note things will also look different when https://github.com/monarch-initiative/dipper/pull/769 makes its way on dev (synonyms and primary labels will swap).

**Comment by monicacecilia** [comment]
After [monarch-initiative/dipper/pull/769](https://github.com/monarch-initiative/dipper/pull/769) was merged, the display was not updated. It still needs to be fixed.

**Comment by kshefchek** [comment]
In https://github.com/monarch-initiative/dipper/pull/769 we added angle brackets to genotype labels, for example:
for mgi and zfin
```Ube3a[tm1Alb]``` became ```Ube3a<tm1Alb>```

for flybase
```Ube3a<sup>C941A.UAS</sup>``` became Ube3a[C941A.UAS]```

Meanwhile in the app we run text through a sanitizer that removes any html tags except sup and img, so Ube3a<tm1Alb> becomes Ube3a

Optimally, dipper would ingest the html encoded label and the clean label and the search indexer would grab Ube3a<tm1Alb> and golr would grab Ube3a<sup>tm1Alb</sup>

The short term solution is to remove the [html sanitizer](https://github.com/monarch-initiative/monarch-ui/blob/25677340/src/App.vue#L27) from the app, or assume that angle brackets should be converted to sup tags (for flybase labels, regular brackets should be converted to sup tags).

If we go this route we need to make sure not to incorrectly change hgvs labels, which contain right angle brackets but not left.

**Comment by vincerubinetti** [comment]
Working on the new 3.0 UI, and it's quite jarring to see variant names like `Shh<tm2(cre/ERT2)Cjt>`. I can easily make it such that `something<blah>` gets transformed to `something<sup>blah</blah>` and gets rendered properly as html, but it sounds like that does not cover all the desired cases, and could even lead to *incorrect* formatting in some cases.

Can someone give me an update on this? @falquaddoomi Do you have time to take a look and see what would be involved here?

**Comment by falquaddoomi** [comment]
@vincerubinetti Sure, I can take a look.

Some comments on the discussion so far: I can't speak to the science, but from a purely web dev standpoint, I think whatever frontend consumes the API should perform the formatting, but the API should definitely return a representation that can be unambiguously formatted, and ideally in an established variant format (if such a thing exists for all the species we're dealing with). Returning HTML for a variant name from an API strikes me as problematic, since non-browser clients might also consume the API and have to deal with removing the formatting.

Perhaps if we've decided that pairs of angle brackets with no intervening brackets always indicate a genomic feature and we know there won't be actual HTML in the string, too, we can use a regex to parse them into `<sup>` tags and not disturb unpaired HGVS brackets...?

**Comment by vincerubinetti** [comment]
> but the API should definitely return a representation that can be unambiguously formatted

Yeah this is my concern, this is what I need.

> Returning HTML for a variant name from an API strikes me as problematic, since non-browser clients might also consume the API and have to deal with removing the formatting

I do not understand any of the science here, but I thought it would be easier for everyone if every entity was in some kind of consistent format for super/subscripts. Another option could be to have another separate label field for any special html formatting, similar how other biolink endpoints return html strings for highlighting and such.

If someone can assure me that `<something>` will always indicate a super script and never mess anything up unintentionally, I'd be happy to include it in the frontend. It just seems like from the comments above that it's not that clean cut.
