### ISSUE TITLE
Improve feedback mechanisms

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#109]
Create and maintain a Monarch initiative helpdesk.

Some ideas include: 
- Creating a helpdesk in a platform that allows users and providers to link to link to issues on GitHub
-  Using the issue / ticket system in GH as the helpdesk. We have already received some feedback from the community saying that GH would not be an inviting environment for professionals who are not familiar with software development environments.

**Comment by pnrobinson** [comment]
Decision: Link out to GitHub page.
- Monarch HelpDesk repository
- Choose templates similar to the HPO webpage
@nlharris to make templates
bottom right or @monicacecilia to provide mockup

**Comment by monicacecilia** [comment]
@nlharris - Thank you in advance! :bowtie:  

I created a repo for you to tackle issue templates at https://github.com/monarch-initiative/helpdesk

I think we should think of using this mechanism of discernment before users start writing tickets, as seen on this [helpdesk](https://github.com/geneontology/helpdesk/issues/new/choose) (you may be the one who created these, actually? either you or @kltm) Screenshot provided below for reference:

![Screen Shot 2019-07-09 at 11 56 41 AM](https://user-images.githubusercontent.com/1714621/60915526-e67bf200-a240-11e9-8eaf-0f56cbb97529.png)

**Comment by monicacecilia** [comment]
With regards to the position of the link for help, I have a new suggestion: 
- [ ] Eliminate the bottom icon and link to 'Contact us'
- [ ] Create a NEW top level menu labeled as 'Help.' Locate this top-level menu to the right of the 

Under this menu item, we should have:
- [ ] A link out to a new page with details on how to reach us either via email or by filing a ticket in the new helpdesk repo. This sub-menu item should be labeled 'Contact Us.'
- [ ] ~~A link to Monarch FAQs (if we have them?). If not, then let's not create one yet.~~ 
- [ ] A link to the page on 'Citing Monarch' ([visible here on website](https://beta.monarchinitiative.org/about/citing); [here is the code on GitHub](https://github.com/monarch-initiative/monarch-ui/blob/master/src/views/Citing.md)). This page is currently linked from the 'About' top level menu, and it should be moved to the 'Help' menu.  
- [ ] Add a new page with information from the legacy page on [how to 'Link to us'](https://monarchinitiative.org/page/links), and a menu item under 'Help' as well to link to it. 

@pnrobinson @cmungall - what do you think?

**Comment by kltm** [comment]
@monicacecilia Our categories are not great, but we're working on them. As https://github.com/geneontology/helpdesk/tree/master/.github/ISSUE_TEMPLATE

**Comment by iimpulse** [comment]
@monicacecilia 

Need content for Contact Us & top of Link To Us. Feel free to send via email if its easier. michael.gargano@jax.org


<img width="1647" alt="Screen Shot 2019-07-10 at 3 01 25 PM" src="https://user-images.githubusercontent.com/7397665/60997123-151ec900-a324-11e9-9bba-808599b0bd25.png">


<img width="1104" alt="Screen Shot 2019-07-10 at 3 01 18 PM" src="https://user-images.githubusercontent.com/7397665/60997128-18b25000-a324-11e9-88ab-8d3512c1b0c1.png">

**Comment by monicacecilia** [comment]
Thanks, @kltm!

**Comment by monicacecilia** [comment]
@iimpulse thanks for working on this!

- This is the text to be added at the top of the 'Link to Us' page: 
```To link to Monarch, please refer to the following tables.```

- Also for the 'Link to Us' page, may I kindly ask that you please revert the changes so the three columns are visible? I actually think it is best to have the URL, without the examples column, but for the time being, let's keep all three of them. Thank you in advance. :bowtie: 

- Text for 'Contact Us' page: .... sending an email with content.

**Comment by jmcmurry** [comment]
Note that we also have a public helpdesk gitter room [here](https://gitter.im/monarch-initiative/helpdesk?utm_source=share-link&utm_medium=link&utm_campaign=share-link):

**Comment by kshefchek** [comment]
also a little bit of history here: https://github.com/monarch-initiative/monarch-app/projects/1

**Comment by monicacecilia** [comment]
Hi @iimpulse - Could I please kindly ask you to update the 'Contact us' text to be aligned to the left (instead of centered), and not italicized. Apologies for the delay adding these two requests. Thank you!

**Comment by monicacecilia** [comment]
I'm re-opening this issue because there is still work to be done. 
@nlharris please see instructions [above](https://github.com/monarch-initiative/monarch-ui/issues/109#issuecomment-509768782).
- [ ] create templates for Monarch helpdesk

**Comment by nlharris** [comment]
Templates done: https://github.com/monarch-initiative/helpdesk/issues/new/choose
I also added some preliminary content to the Help Desk home page (needs fleshing out, but some of it will depend on the new website): https://github.com/monarch-initiative/helpdesk

**Comment by monicacecilia** [comment]
@nlharris - for the Readme, please use the text (and links) found here instead: https://beta.monarchinitiative.org/help/contact

Also, please remember to review this [document for contributions to Monarch](https://github.com/monarch-initiative/monarch-app/blob/master/CONTRIBUTING.md). 😉

**Comment by monicacecilia** [comment]
@nlharris THANK YOU for the templates! :bowtie: 
I'll close once the ReadMe is updated.

**Comment by nlharris** [comment]
ok to close now?

**Comment by monicacecilia** [comment]
Yep. This looks now complete. Thanks everybody! :bowtie:
