### ISSUE TITLE
Clean up.

### ISSUE THREAD

**Issue by iimpulse** [monarch-initiative/monarch-ui#114]
This issue is to cleanup the current front-end work, including but not limited to css, file formatting, folder structure.

**Comment by kshefchek** [comment]
Can you document or describe here what can be improved?  My understanding was that we are following best practices but it's also not my domain.  Note that the directory structure is generated from running the vue CLI - we should try to be as idiomatic as possible.

**Comment by iimpulse** [comment]
I didnt go as overboard. There were just visual things that I saw that would be an enhancement, as well as some of the line breaks in the files.
