### ISSUE TITLE
Hitting Escape or losing focus should clear all dropdowns

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#12]
Both in homepage and navbar searches

**Comment by nathandunn** [comment]
The problem is that it fails to bubble down the escape key down in the search bar itself (it works, or at least it used to) if you had bubbled down correctly.

**Comment by jmcmurry** [comment]
I don't understand what this means. Can you describe what needs doing? This is important.

**Comment by nathandunn** [comment]
If you are clicked in the search box (it has focus), then hitting escape will close clear all search inputs and dropdown.  

If it does not have focus, then it any actions will not provide any behavior. 



Looking at how google behaves, though, I think it should be:

- when hitting escape OR losing focus (e.g., clicking somewhere else or hitting tab), the drop down disappears, but the search input remains

**Comment by nathandunn** [comment]
I think that will be an easier fix and more consistent ui-wise.
