### ISSUE TITLE
Fix size font for tweets feed

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#122]
On https://beta.monarchinitiative.org/, the font size of the twitter feed is much bigger than the news.  
I think the landing page needs a complete rethink anyway, but we will also need to adjust the twitter feed. @monicacecilia @jmcmurry What is our current thinking on the design of the main landing page?

**Comment by monicacecilia** [comment]
Yes, I think the div/column containing the tweeter feed is too wide, and it changes dynamically with the size of the page. 

Maybe we can readjust to fix the width to a max of 300px - or insert the feed into a block and restrict the size of that block to ~300px. 

Maybe one of the newly minted vue experts could change this? :bowtie:

**Comment by monicacecilia** [comment]
This was fixed in #136.
