### ISSUE TITLE
Extend tests for UI

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#124]
As part of the MVP for the UI, we need to extend the tests that Dan already prepared, found here https://github.com/monarch-initiative/monarch-ui/tree/master/tests

Example: 
https://github.com/monarch-initiative/monarch-ui/blob/master/tests/e2e/specs/disease.js

Tests on legacy:
https://github.com/monarch-initiative/monarch-app/tree/master/tests

**Comment by iimpulse** [comment]
@kshefchek will look at the e2e tests for this framework, always something funky with selenium and chrome drivers.

**Comment by kshefchek** [comment]
this shouldn't block the release, moving to 1.1

**Comment by monicacecilia** [comment]
Our current UI has implemented beautiful tests put in place by Vince. Closing this. :bowtie:
