### ISSUE TITLE
Too many disease models

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#125]
https://monarchinitiative.org/model

On this page, too many irrelevant models are shown. Can we choose a stricter threshold/cutoff?

**Comment by kshefchek** [comment]
my understanding is that we're leaving these pages behind (along with the barcharts), is that still correct @monicacecilia @jmcmurry ?

**Comment by monicacecilia** [comment]
Yes, that is my understanding as well. We are not planning to move this page over to the new monarch-ui. 
I have just started a super keeping track of pages, decisions, new paths, tickets (when applicable) and whether the migration has been completed or not. See #128
