### ISSUE TITLE
Add string interaction widget to gene pages

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#127]
We're interested in adding the string protein-protein interaction widget to our gene pages, eg https://string-db.org/cgi/network.pl?taskId=F8P51VTtMO5w

Steps:
- Contact their helpdesk for more info (or refer to online docs)
- Add widget to gene overview

**Comment by monicacecilia** [comment]
Perhaps @mellybelly can facilitate the start of communication.

**Comment by kshefchek** [comment]
https://string-db.org/cgi/help.pl?sessionId=k0J93FgEclFs
