### ISSUE TITLE
Update Downloads page

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#133]
In this page https://archive.monarchinitiative.org/latest/ we need to add a ReadMe file.

**Comment by kshefchek** [comment]
accidentally created a dupe here https://github.com/monarch-initiative/MonArchive/issues/3, closed that in favor of keeping this one

**Comment by monicacecilia** [comment]
🎉 - just pinging to bring back up to top of your inbox (as promised). 😃

**Comment by monicacecilia** [comment]
Hi @kshefchek - as we agreed on our last ui-check in, this is meant to be closed by tomorrow, Friday 13-March,2020. ping!

**Comment by kshefchek** [comment]
draft here: https://github.com/monarch-initiative/MonArchive/pull/4

hoping for @TomConlin and @monicacecilia's review

**Comment by monicacecilia** [comment]
Reviewed! Thanks @kshefchek :bowtie: 
https://github.com/monarch-initiative/MonArchive/pull/4 will close this. 🙌
