### ISSUE TITLE
Update FlyBase icon used in the 'source' column (and maybe elsewhere)

### ISSUE THREAD

**Issue by sjm41** [monarch-initiative/monarch-ui#134]
For indicating FlyBase data within Monarch, please use a icon based on the graphic on the top-left of any FlyBase page, e.g. http://flybase.org/

**Comment by monicacecilia** [comment]
Hi @sjm41 - 

Thanks for submitting a ticket to this repository for the new website for the Monarch Initiative. I assume that you are browsing our beta site, still under development at https://beta.monarchinitiative.org/  

Please note that we are still maturing the content and capabilities of this site, and that content, features, and behaviour are still rapidly changing on a regular basis. 

Could I kindly ask that you please include the URL for the page (or query you used) where you found the  logo in mention that you wish to change in the new monarch-ui? 

Thank you!

**Comment by monicacecilia** [comment]
Icon has been updated. See https://beta.monarchinitiative.org/about/data-sources and click on 'More Info' under FlyBase to display.
