### ISSUE TITLE
Update the About Monarch page

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#135]
With great ideas from @pnrobinson, we should update the 'About Monarch' page with the text provided below. Images and figure legend details to be provided later. 
monarch-ui path: monarchinitiative.org/about/monarch

<code>

The Monarch Initiative is an integrative data and analytic platform connecting phenotypes to genotypes across species. The correlation of phenotypic outcomes and disease with genetic variation and environmental factors is a core pursuit in biology and biomedicine. 

We have created or currently contribute to many essential bio-ontologies that together enable sophisticated and semantically integrated computational analysis across gene, genotype, variant, disease, and phenotype data. We lead the development of the Human Phenotype Ontology, (linkto HPO site) which is used across the world for genomic diagnostics in genetic disease and other areas. We have created Mondo (linkto Mondo site), a unified disease ontology that represents the most comprehensive integration of disease entities ever achieved. We are a Driver Project for the Global Alliance for Genomics and Health (GA4GH, linkto: https://www.ga4gh.org/), and are major contributors to the development of genomics standards within GA4GH. We have developed algorithms and tools that are in use by multiple communities for tasks including the identification of animal models of human disease through phenotypic similarity, phenotype-driven computational support for differential diagnostics, and translational research.

</code>

After that, we should include images to represent the following: 
- Picture 1--the Washington eye picture. Caption. Find out more about cross specific phenotype analysis. We need to have a separate page that describes this, but to start off with it would be helpful just to provde a list of the major pubmeds such as Washington, uberon, uberpheno, Exomiser

- Picture 2--the HPO hierarchy that we have been using in recent presentations. Caption. The Human Phenotype Ontology. Link to HPO page and to most recent NAR2019 article.

- Picture 3 -- Phenopackets graphic. Link to the GitHub repo and the read the docs

- etc. We should have at least six figures with captions that link to the most interesting resources.

**Comment by iimpulse** [comment]
@pnrobinson do you have links for the hpo hierarchy picture and phenopackets graphic?

**Comment by pnrobinson** [comment]
@jmcmurry Julie has a number of very nice HPO hierarchy graphics -- Julie, could you please provide your favorite one? 
We do not currently have a great graphic for Phenopackets, but again Julie has a number of figures we used in recent grant proposals and perhaps one of them can be simplified a bit for the Monarch homepage?

**Comment by monicacecilia** [comment]
## Bringing suggestions here from #65 

### 3. Update contents in About page by adding this text to the top of the page: 
- Body of text: <code> The Monarch Initiative is an integrative data and analytic platform connecting phenotypes to genotypes across species, bridging basic and applied research with semantics-based analysis. The correlation of phenotypic outcomes and disease with genetic variation and environmental factors is a core pursuit in biology and biomedicine. </code>
- [ ] Task has been completed. 

 -------

### 4. Add a figure and legend to the page as shown below. We can discuss updating the image as needed.
- Figure legend: Title in bold: ```The phenotype annotation coverage of human coding genes.```  Legend: <code>This figure shows the availability of curated phenotypes that have been attributed to human genes (directly or inferred via orthology) across a range of model organisms (teal circle). Phenotypes for human genes curated in humans are shown in green, and they only represent 20% of the total number of protein-coding genes in the human genome (HGNC, 07-2019). Data from more species raises the phenotypic coverage of human coding genes to 82%.</code>. 
- [ ] Task has been completed. 

![phenotype-cov-hum-2](https://user-images.githubusercontent.com/1714621/61692753-80a66480-ad2e-11e9-86ba-89d7b5b3bb2a.jpg)

**Comment by monicacecilia** [comment]
Also need to add these figures to the 'About' page (not yet included in #140): 

- [ ] Figure of the HPO hierarchy that we have been using in recent presentations. Caption. The Human Phenotype Ontology. Link to [HPO page](https://hpo.jax.org/) and to [most recent NAR2019 article](https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cphg.92).

- [ ] Figure about Phenopackets. Link to the GitHub repo and the read the docs

Dear @jmcmurry -  @pnrobinson issued a request for updated version of these figures ([see above](https://github.com/monarch-initiative/monarch-ui/issues/135#issuecomment-512405797)). When you get a chance, could we please see about adding updated images for HPO hierarchy and for Phenopackets? 

I think we are probably looking for updated versions of the following: 

### HPO Hierarchy
<img width="890" alt="Screen Shot 2019-08-01 at 11 20 00 AM" src="https://user-images.githubusercontent.com/1714621/62317346-57808500-b44e-11e9-945b-83f8784bd830.png">

--------------------------

### Phenopackets 
<img width="889" alt="Screen Shot 2019-08-01 at 11 20 49 AM" src="https://user-images.githubusercontent.com/1714621/62317400-797a0780-b44e-11e9-946d-4303fdbf0fef.png">

**Comment by monicacecilia** [comment]
@iimpulse updated figure for 'phenotype coverage' can be found [here](https://github.com/monarch-initiative/monarch-ui/blob/master/src/assets/img/phenotype-cov-hum-5.png).

**Comment by monicacecilia** [comment]
@iimpulse I have added an updated figure for HPO [here](https://github.com/monarch-initiative/monarch-ui/blob/master/src/assets/img/HPO-figure-for-monarchui.png). We can use this as a place holder for now.

**Comment by monicacecilia** [comment]
An alternative for Phenopackets figure - 'The Phenopackets Ecosystem'

![Phenopackets-ecosystem2](https://user-images.githubusercontent.com/1714621/62501601-71003480-b7a0-11e9-87dd-e8414bbf2ee7.png)

**Comment by monicacecilia** [comment]
Newly updated figure for phenotype coverage can be found [here](https://github.com/monarch-initiative/monarch-ui/blob/master/src/assets/img/phenotype-cov-hum-6.png). The file name is phenotype-cov-hum-6.png
See [this comment](https://github.com/monarch-initiative/monarch-ui/pull/140#discussion_r310906708) in #140 for further details.

**Comment by monicacecilia** [comment]
@iimpulse - to help us keep a mental count of the components of this page, I put together a mockup that combines all the information we have listed in this ticket. This should allow us to remove the blocker for now. 

- This mock up lists all the components that should go in this page, but it should not be a guide for styling. 😉Unless we manage to capture any suggestions, please use your best judgement to organize the content with the elements I have provided below.  

- The text and legends in this mock up can can be found in this file: 
[monarch-ui-about-page-text-1.txt](https://github.com/monarch-initiative/monarch-ui/files/3471009/monarch-ui-about-page-text-1.txt)

- Figures 2, 3, and 4 can be found in [this images directory](https://github.com/monarch-initiative/monarch-ui/tree/master/src/assets/img). Details to display Figure 1 are found in [this file](https://github.com/monarch-initiative/monarch-ui/blob/master/src/views/AboutMonarch.md). 

![monarch-ui-about-page1](https://user-images.githubusercontent.com/1714621/62521912-6d42d100-b7e5-11e9-96a9-5e9d3d5b37a8.png)

**Comment by jmcmurry** [comment]
Thanks Moni; this looks great

**Comment by iimpulse** [comment]
#140
