### ISSUE TITLE
All pages should have configurable banner

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-ui#143]
We have a mechanism for including a beta banner on all beta pages

This works:
- http://beta.monarchinitiative.org/analyze/phenotypes
- http://beta.monarchinitiative.org/disease/OMIM:183090

Doesn't have it:
- http://beta.monarchinitiative.org/
- http://beta.monarchinitiative.org/page/about

(btw beta==tartini)

**Comment by kshefchek** [comment]
Transferring from monarch-app, I think we should include a banner on beta pages that include a warning about data quality, in light of our recent clinvar bug.

**Comment by monicacecilia** [comment]
@iimpulse This would be a configurable banner in ALL the pages. 'beta' in the initial description simply refers to the new monarch-ui.
