### ISSUE TITLE
Anatomy nodes are not loading

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#147]
https://iimpulse.github.io/monarch-ui/anatomy/UBERON:0001890

**Comment by monicacecilia** [comment]
@jmcmurry Could you please explain the expected behaviour? 
I can see this (below) right now. What's missing?

<img width="995" alt="Screen Shot 2019-07-31 at 2 25 08 PM" src="https://user-images.githubusercontent.com/1714621/62249347-09f90f00-b39f-11e9-883c-e3aa4cb90f3f.png">

**Comment by monicacecilia** [comment]
Responsiveness improved for @jmcmurry
