### ISSUE TITLE
Recover label for term pages

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#148]
There are so many great improvements on the term pages! Information is tighter, better organized, and  I am in agreement with discarding the icons + counts on the 'landing' page for some of the terms.

Now for the action items: 

- [x] After #145,  we have lost the label that identified the term / category we are inspecting in a page. For example, to the left of the dotted yellow line, we have the current visualization for term pages (previous viz. on the right). We need to recover those, please. It helps users to get orientated when they reach a page. 

![label-synonym-monarch-ui-ticket](https://user-images.githubusercontent.com/1714621/62255751-6d8d3780-b3b3-11e9-865f-fc67b6e16d20.png)

I also added a note about losing the synonyms from the header bar, but I can be talked out of restoring those. :bowtie:

**Comment by iimpulse** [comment]
The issue i have with the label, is that it looks like its part of the menu when infact its not. I think we need a better way of showing that and I'll think of a way. The synonyms are not going to work in that bar, they are on the overview page now and will most likely make a table for them or something to that effect.

**Comment by monicacecilia** [comment]
Great. I look forward to seeing your suggestions for where the category label could go. 

Yeah, I don't miss the synonyms.
