### ISSUE TITLE
Update Monarch Team page

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#153]
In the '___Monarch Team and Collaborators___' page, please update the information detailed below. The source [file (yaml) can be found here](https://github.com/monarch-initiative/monarch-ui/blob/master/public/team.yaml). Although this page is linked to the 'About Team' markdown file, you won't need to modify that  markdown file.

- Under '___Participating Institutions___'
  - In the OSU team: 
    - [x] Remove Dan Keith
    - [x] List Moni after Julie
  - In the JAX team:
    - [x] Add Michael Gargano
    - [x] Add Vida Ravanmehr
  - In the QMUL team: ~~(@julesjacobsen, please confirm that this is ok, or add request to not remove. Please check below as well. Thank you!)~~
    - [x] Remove Tomasz Konopka
    - [x] Remove Pilar Cacheiro

- Below, in the section that lists biographies for each collaborator:
  - In the '___Oregon State University___' list:
    - [x] Move Dan Keith to the alumni list. Remove biography and photograph. Label this entry as '_Dan Keith (Bioinformatics Semantic Engineer)_.' Place entry after Tim's.
  - In the Berkeley list:
    - [x] Add Seth Carbon's picture, which can be now found [here](https://github.com/monarch-initiative/monarch-ui/blob/master/public/img/team/SethCarbon.png).
    - [x] Add biography and picture for Eric Douglas. 
       -  @dougli1sqrd please provide us with your photograph and biography to complete this step. Thank you!
  - In the JAX list: 
    - [x] Add biography and picture for Michael Gargano. 
       -  @iimpulse please provide us with your photograph and biography to complete this step. Thank you!
    - [x] Add biography and picture for Vida Ravanmehr
       - Need to send an email to Vida to request info for her profile. 
  - In the QMUL list:
    - [x] Create a list for 'Alumni'
    - [x] Move Tomasz Konopka to the alumni list. Remove biography and photograph. Label this entry as '_Tomasz Konopka (Bioinformatician)_.'
    - [x] Move Pilar Cacheiro to the alumni list. Remove biography and photograph. Label this entry as '_Pilar Cacheiro (Computational Biologist)_.'

**Comment by nicolevasilevsky** [comment]
emailed Vida on 08/06 to ask for picture and bio

**Comment by monicacecilia** [comment]
Biography and pic for @dougli1sqrd were added in #160.

**Comment by monicacecilia** [comment]
Brilliant. Thanks @nicolevasilevsky :bowtie:
