### ISSUE TITLE
Create temporary static /sources page until source data can be loaded from biolink-api

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/monarch-ui#156]
Per request from @monicacecilia, making this issue to make a static page using the [current monarch app sources page](https://monarchinitiative.org/about/sources), until data for the new sources page can be loaded from the biolink-api

**Comment by monicacecilia** [comment]
Thank you, @justaddcoffee 
This page would replace the current place holder, https://beta.monarchinitiative.org/sources
The page is linked to from the '_About_' top level menu as ```About/Data Sources```

**Comment by monicacecilia** [comment]
@justaddcoffee - no worries. I'm going to assign @iimpulse because he has time to make a static page this week. Please keep doing your magic on the dipper side! :bowtie:

**Comment by justaddcoffee** [comment]
okies
