### ISSUE TITLE
Update Phenotype Profile Search to use BioLink to generate table view

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#161]
https://beta.monarchinitiative.org/analyze/phenotypes uses biolink for phenogrid, but is still using https://monarchinitiative.org/analyze/phenotypes.json to generate the table view

**Comment by monicacecilia** [comment]
Dear @iimpulse, please remember to update this ticket with your brilliant progress. :bowtie:

**Comment by iimpulse** [comment]
Need to upgrade phenogrid on NPM, use download from specific branch for now and deploy this to BETA

**Comment by kshefchek** [comment]
Looking at this on beta, we still use the legacy api to generate the table view, for example when I take the phenotypes for marfan and search against all I see this network call:

https://monarchinitiative.org/analyze/phenotypes.json?&input_items=HP:0000678%2CHP:0000218...&gene_items=undefined&target_species=all&mode=search

note this is the table that shows up under phenogrid, it is a vue-bootstrap table driven from the monarch-ui code

**Comment by iimpulse** [comment]
What's the biolink solution here?

**Comment by kshefchek** [comment]
my understanding is that it's a ui issue, perhaps this component https://github.com/monarch-initiative/monarch-ui/blob/master/src/components/PhenotypesTable.vue

that calls
https://github.com/monarch-initiative/monarch-ui/blob/master/src/api/BioLink.js#L537
