### ISSUE TITLE
Update taxon filter to remove 'facets' filter

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#168]
___FOR NOW___, a decision has been made to remove the current 'facets' filters shown on the left column of our results  pages and instead: 
- [x] create a taxon filter on the right side of the results pages (a table filter)
- [x] add this filter ONLY to pages with gene results

_Don't @ me._ :bowtie:

**Comment by monicacecilia** [comment]
Somewhat related to #29  - @jmcmurry perhaps we should consider punting #29 to the [Monarch-UI v1.1 milestone](https://github.com/monarch-initiative/monarch-ui/milestone/1) in favour of this ticker, for now.

**Comment by iimpulse** [comment]
@kshefchek @monicacecilia 

There are only a few card types that "have taxon". Previously.. we were building facets based off the total card counts and when selecting/deselecting a taxon, it would update the counts. When moving to a table level taxon we need the counts per taxon based on the card type.. 

For example homolog or genotype.  But since we are paginating I only have unique taxon counts for that page.

<waiting on ticket ref>

**Comment by monicacecilia** [comment]
Ping to @deepakunni3 as well.

**Comment by kshefchek** [comment]
If you set facet=true when getting the data it should return some meaningful facets, but it looks like it's hard coded for subject_taxon_label and object_closure.  It would be useful to make this configurable at the API level similar to solr, ie a facet_field param.

**Comment by monicacecilia** [comment]
We need some @deepakunni3 awesomeness. right.here. Haaaalp! 🙏

**Comment by monicacecilia** [comment]
Also, related to a discussion held in #29

**Comment by kshefchek** [comment]
this should be on dev now, https://api-dev.monarchinitiative.org/api/bioentity/gene/NCBIGene%3A3630/homologs?rows=0&facet=true&facet_fields=object_taxon&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false

Or alongside the data
https://api-dev.monarchinitiative.org/api/bioentity/gene/NCBIGene%3A3630/homologs?rows=100&facet=true&facet_fields=object_taxon&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false

**Comment by iimpulse** [comment]
So, I've almost fully implemented this, there seems to be a few endpoints under gene that don't support "taxon" by array. When that is cleared I think this ticket is finished.

/gene/{id}/homologs
/gene/{id}/variants

**Comment by iimpulse** [comment]
@deepakunni3 looks like variants endpoint is still not filtering correctly in dev

**Comment by deepakunni3** [comment]
@iimpulse This should be now fixed on api-dev

**Comment by monicacecilia** [comment]
Work also being done at https://github.com/monarch-initiative/dipper/issues/860

**Comment by iimpulse** [comment]
Updates on how to proceed?

**Comment by kshefchek** [comment]
I've added some code to biolink to query taxa directly, which should fix the odd filter behavior.  However, we're having network issues on our servers and I can't stage the changes on api-dev.  Essentially it will be adding a new param, direct_taxon=true, when loading the tables.  If you want to get your PR ready I can just update it when the api is ready.

**Comment by kshefchek** [comment]
@iimpulse to filter on a taxon/taxa directly, add direct_taxon: true to the params, for example
https://api.monarchinitiative.org/api/bioentity/gene/HGNC%3A10896/variants?rows=100&direct_taxon=true&taxon=NCBITaxon:9606
