### ISSUE TITLE
Update publications page

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-ui#170]
Two things:
1) Perhaps this is premature to suggest changes for the publications page (https://beta.monarchinitiative.org/about/publications), but it is really hard to read the titles - I can tell they are bold but the bond font doesn't look very different and the titles are hard to read.

2) the PubMed link for the 2017 NAR paper is wrong.

Mungall CJ, McMurry JA, Köhler S, Balhoff JP, Borromeo C, Brush M, Carbon S, Conlin T, Dunn N, Engelstad M, Foster E, Gourdine JP, Jacobsen JO, Keith D, Laraway B, Lewis SE, NguyenXuan J, Shefchek K, Vasilevsky N, Yuan Z,Washington N, Hochheiser H, Groza T, Smedley D, Robinson PN, Haendel MA (2017) The Monarch Initiative: An Integrative Data and Analytic Platform Connecting Phenotypes to Genotypes across Species. Nucleic Acids Research 45(D1):D712–22. [pubmed]
It incorrectly links to:
http://www.ncbi.nlm.nih.gov/pubmed/30476213

**Comment by monicacecilia** [comment]
Dear @iimpulse, in the publications page:
- [ ]  Would you mind please having a look at the publications page and perhaps see about suggesting an improvement that can facilitate reading the titles? I see what @nicolevasilevsky is saying, and the bold text is not very different from the rest. 
- [ ] Very important to correct this: the Monarch 2017 NAR paper should link instead to https://www.ncbi.nlm.nih.gov/pubmed/27899636

**Comment by monicacecilia** [comment]
- [ ] Update path for the publications page. Current path is ```/about/publications``` but it has to be ```/documentation/publications``` instead.
