### ISSUE TITLE
Remove hrefs for obo purls ending in PHENOTYPE

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#171]
As a background:
https://github.com/monarch-initiative/dipper/issues/741
https://github.com/obophenotype/upheno/issues/521

Example:
https://beta.monarchinitiative.org/phenotype/GO:0022008PHENOTYPE

**Comment by kshefchek** [comment]
It looks like many of our obo purls do not resolve, we should add to the list:
http://purl.obolibrary.org/obo/GARD_
http://purl.obolibrary.org/obo/MESH_
http://purl.obolibrary.org/obo/SCTID_
http://purl.obolibrary.org/obo/ICD9_

I'm sure there are many more, @TomConlin I think you cataloged these at one point?

**Comment by TomConlin** [comment]
There are enough to consider it deliberate. 
I focused on rescuing our data identifiers

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/monarch-ui/pull/224
