### ISSUE TITLE
Create a new Phenotype Curation Guidelines page

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#174]
- [ ] Using the guidelines as they were published on the latest Current Protocols paper ([here](https://currentprotocols.onlinelibrary.wiley.com/doi/abs/10.1002/cphg.92)), create a new page titled 'Phenotype Curation Guidelines.' 
- [ ] In the top-level menu 'Documentation,' replace current link out to blog post on medium with this new page under the 'Phenotype Curation Guidelines' submenu.

**Comment by monicacecilia** [comment]
- [ ] Path for the new page should be ```/documentation/curationguidelines```

**Comment by pnrobinson** [comment]
I think this should be on the HPO webpage for the clinical guidelines. I think that unfortunately we need to wait a year for the article to go onto PMC. Also note that it is premature to talk about curation guidelines (we are the ones doing it!) and the article is talking about annotating individuals.

**Comment by monicacecilia** [comment]
Ticket issued by @mellybelly's suggestion. Tagging here to get her attention to address @pnrobinson's valid points.

**Comment by mellybelly** [comment]
@pnrobinson there used to be a monarch blog I wrote that had the patient-level curation guidelines from the UDP, this is not about HPO disease curation. I think the page should be posted in both sites, but what Moni and I were brainstorming was an update from the blog, especially since users won't be able to get to the current protocols manuscript.

**Comment by monicacecilia** [comment]
[This is the blog post](https://medium.com/@MonarchInit/how-to-annotate-a-patients-phenotypic-profile-afc5773d6cdb) currently linked from ```Documentation``` top level menu, in the submenu item ```Phenotype Curation Guidelines```. This page was moved from monarch-app (legacy site) to monarch-ui (new, beta site).

**Comment by mellybelly** [comment]
@monicacecilia where do you want me to put the content?

**Comment by iimpulse** [comment]
https://github.com/monarch-initiative/monarch-ui/tree/feature/phenotype-guidelines

The branch is here with the page under src/views/PhenotypeCurationGuidelines.md

I've added the blog post for now and you can update accordingly. This also has a hotfix for the node page banner.

**Comment by pnrobinson** [comment]
I am worried that we should not have two competing versions of this material, and currently there is a lot of documentation related to this on the HPO site. Can we make a shorter version here and link to the HPO site? The HPO site needs to have a link to the new Protocols paper. Also, we should consider talking about guidelines for model curation that will go here.

**Comment by monicacecilia** [comment]
Currently, the link for 'Phenotype Curation Guidelines' is a re-direct to the blog Melissa wrote on Medium, five years ago. 

Earlier in this ticket: 
- @pnrobinson proposed to _make a shorter version of this page [on the Monarch UI] and link to the HPO site_
- @mellybelly had concerns that _the patient-level curation guidelines from the UDP, [are] not about HPO disease curation_ and that she would like to update the Monarch Blog entry she wrote about it and place that content in this page instead. 

@pnrobinson, @mellybelly, may I kindly ask that you please decide on what would be the best course of action and share the response (and preferred content) with us? We are down to the wire now and need to figure out what to do with this page. 

Thank you!

**Comment by pnrobinson** [comment]
Can we revisit after the proposal is out the door? I think we will want to add a lot more stuff and so we could just leave things as they are for now and plan to come back to this when we have time

**Comment by monicacecilia** [comment]
I like the sound of that. We can come back to revisit at a later time. It won't be show stopper for release, then. Thank you, @pnrobinson.

**Comment by monicacecilia** [comment]
Proposals are out the door, and we're itching for a v1.0 release (in approximately 1 week). 
In the absence of activity on this ticket, I'm making a decision to punt it to a future enhancement sprint, after v1.0 is out the door.

**Comment by monicacecilia** [comment]
This ticket died in solitude and abandonment.
