### ISSUE TITLE
Monarch mailing lists--contact page needs links

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-ui#175]
https://beta.monarchinitiative.org/help/contact says "Subscribe to one or both of these lists to follow general developments and discussions, or to post a message to the Monarch community: 
monarch-friends mailing list
monarch-users mailing list" but these are not linked nor is any other way provided to find and subscribe to the lists.

**Comment by monicacecilia** [comment]
Thanks for the nudge @nlharris. 

This was still in the 'to do' and this is a good reminder. The lists have to be created first, so I'm closing this in favor of #178.
