### ISSUE TITLE
Update path for Monarch Web Services page

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#179]
- [ ] Restore path for ```/about/monarch-web-services``` to display the wonderful work prepared for https://github.com/monarch-initiative/monarch-ui/pull/162

**Comment by monicacecilia** [comment]
1. Trying to access the 'Monarch Web Services' page issues an error that reads 'No such path available: /about/monarch-web-services'

-----

2. 'Monarch Web Services' it is not available as submenu from the 'About' top level menu.
<img width="457" alt="Screen Shot 2019-08-21 at 7 11 44 PM" src="https://user-images.githubusercontent.com/1714621/63480655-8daa9680-c447-11e9-8b1e-3a154a343a6a.png">

**Comment by iimpulse** [comment]
I redployed a different branch, this is in master now. ( unsure when it goes to beta )
