### ISSUE TITLE
Update documentation for how to use Phenotype Profile Search

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#181]
The legacy tool for 'Monarch Phenotype Profile Analysis' included text explaining how to use the different windows and what to expect. See https://monarchinitiative.org/analyze/phenotypes and the screenshot below. 

<img width="1401" alt="Screen Shot 2019-08-23 at 10 20 37 AM" src="https://user-images.githubusercontent.com/1714621/63611973-f30a9e80-c591-11e9-9c87-364525043098.png">

@mellybelly @jmcmurry Is the text in this (legacy) page enough and appropriate for Monarch users? If so, we can transfer these details to the new page. Else, please provide suggestions with additional / less text to add in the new 'Phenotype Profile Search.'

We need your input here so @iimpulse can update the text in the [new 'Phenotype Profile Search'](https://beta.monarchinitiative.org/analyze/phenotypes) accordingly (see screenshot below).

<img width="999" alt="Screen Shot 2019-08-23 at 10 38 10 AM" src="https://user-images.githubusercontent.com/1714621/63612063-2d743b80-c592-11e9-9018-582902ab835a.png">

**Comment by monicacecilia** [comment]
Thanks @jmcmurry. We should start with adding the text back to the examples, and create a new ticket for an automatically filled / previously generated example to be done afterwards for these comparisons. 

@iimpulse - Thanks for suggesting this. Here is your next ToDo. Thank you!

**Comment by jmcmurry** [comment]
Reminder that a description of how to interpret the phenogrid results is
here; not a bad thing to link to
https://academic.oup.com/view-large/figure/51201718/gkw1128fig6.jpg

>

**Comment by monicacecilia** [comment]
Specs being worked out [here](https://docs.google.com/document/d/1uyfHfOvLi9tpKbDOL8eqisv6qdVlqZwkQSoG1PtxL2s/edit).

**Comment by monicacecilia** [comment]
Updates to the documentation and latest decisions on redesign for this tool can be seen in [this ticket](https://github.com/monarch-initiative/monarch-ui/issues/258#issuecomment-593861673).

**Comment by monicacecilia** [comment]
Closing thanks to all of the awesomeness that @iimpulse added with #321. :bowtie:
