### ISSUE TITLE
Update icon images to be used throughout site

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#183]
Update files available in this directory (https://github.com/monarch-initiative/monarch-ui/tree/master/public/img/sources), which are used throughout the site, for example in the [static version of the Sources Page on the beta site at https://beta.monarchinitiative.org/sources

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/monarch-ui/pull/191
