### ISSUE TITLE
Create new page for Disclaimer

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#184]
Create a new page in the Monarch beta site to hold the text currently available on the monarch-app page https://monarchinitiative.org/page/disclaimer. The code lives here https://github.com/monarch-initiative/monarch-app/blob/master/templates/page/disclaimer.mustache. However, this text needs to be updated as follows: 
- ~Update all instances of 'Oregon Health and Science University' to 'Oregon State University'~
- ~Update all instances of 'OHSU' to 'OSU'~
- [x] Update the language of [this line](https://github.com/monarch-initiative/monarch-app/blob/master/templates/page/disclaimer.mustache#L10) to read instead: ```You are here identified as a recipient of one or more Monarch Initiative software and/or data collection tools, including but not limited to the Exomiser, (hereby referred to as “Monarch Tools”) developed by Oregon Health and Science University ("OHSU")). OHSU provides you the Monarch Tools under the following limitations.```
- [x] Update the submenu item 'Disclaimer' from 'About' top level menu, so that it links out to this new page (it is currently redirecting to the Monarch blog 'home' page).

Although the language of this text was discussed number of years ago, this may be a good opportunity for a sanity check. @jmcmurry, @mellybelly, @kltm - please let us know if you have any comments on the language of this disclaimer. 

@iimpulse, for now, we will simply plan to keep the current text.

**Comment by jmcmurry** [comment]
I am not sure that the IP got transferred officially. We may need to leave it as it is at least for now.

**Comment by monicacecilia** [comment]
Addressed in #185

**Comment by jmcmurry** [comment]
@monicacecilia Should we get an "On ice" label or milestone so that we can flag that we have triaged and deprioritized it?

**Comment by monicacecilia** [comment]
Hi @jmcmurry. A milestone, yes. We have been punting actions (tickets) to this next milestone, https://github.com/monarch-initiative/monarch-ui/milestone/2 - and from there we will encourage us to either 'start working on them' or 'punt them' accordingly. Perhaps it is an unfounded fear, but I'm afraid that using just a label may cause us to lose track of it. (it goes to the background?). 
Does that suffice for what you are looking at?

**Comment by jmcmurry** [comment]
Yes; this is fine. It might end up leading to multiple reassignments, but we can pivot later if needed. I've changed the MS for this present issue accordingly.
