### ISSUE TITLE
Fix display of licensing information and create new 'About Monarch Licensing' page

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#186]
The footer should not give a specific license as this misleads into thinking that the data are ours to license.
- [x] Create a new page with the text on licensing information provided [here](https://docs.google.com/document/d/1xeD2NEZvzVQrn16-oDwodqxVZV04OVX63Ch5yXWQ41s/edit#heading=h.4dzoydelshom). @mellybelly and @kltm  would be grateful for your input.
- [x] In the footer, instead of ```CC-BY 3.0, except where noted```, the anchor text should say ```About Monarch licensing```. 
- [x] Linkout ```About Monarch licensing``` text in footer to the new licensing page (see below).

**Comment by kltm** [comment]
@jmcmurry If somebody is up to a little more data munging, at least for some of the data ingest, you could consume the RDP data as a resource, (possibly) show stars, and link to the licensing data using our metadata.

https://github.com/reusabledata/reusabledata/issues/191
https://github.com/reusabledata/reusabledata/issues/195

W/o RDP hat on, the mockup you have certainly seems to be a lot more informative and easy to use.

**Comment by jmcmurry** [comment]
@kltm that is an interesting stretch goal. It would require non-trivial wiring under the hood to get the source IDs to match. Manual curation in this case seems more tractable since the data isn't that volatile. I would be wary of fetching the wrong thing and then accidentally licensing something inadvertently.

**Comment by jmcmurry** [comment]
What we could do, however, is link out to the corpus of all scores. I'll update the gdoc accordingly.

**Comment by monicacecilia** [comment]
- [ ] Add a link to licensing page for each resource in /sources page.
- [ ] Add a link to (Re)UsableData.org on the Licensing page

**Comment by kltm** [comment]
"The (Re)usable Data Project"
http://reusabledata.org

**Comment by monicacecilia** [comment]
Hi @jmcmurry, @mellybelly, @kltm - Reconnecting about his very old ticket. 

1. Does this Google doc show the contents of the "About Monarch Licensing" page the way you want it to be in its final form on the new Monarch UI?
2. Does your request to 'link out to the corpus of all scores' mean to add licensing information to each of the entries listed as a resource on this page https://beta.monarchinitiative.org/about/data-sources ?

**Comment by justaddcoffee** [comment]
Can we close this ticket? I'm working on putting better ontology license info on this page, but that's captured here #273

**Comment by jmcmurry** [comment]
Yes, thanks; we can close this

**Comment by justaddcoffee** [comment]
+1
