### ISSUE TITLE
Remove SCA2 from list of examples

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#187]
https://beta.monarchinitiative.org/disease/MONDO:0008458

Can we assume that users will immediately grok that this disease is caused by repeat expansions? 
i.e.,  NP_002964.3:p.Gln166(>=33)

Maybe it would be better to use an example that has a few more pathogenic variants?

Alternatively, maybe we can provide some explanation?

Not a major issue, close it if we have other things to think about!

**Comment by iimpulse** [comment]
Removed from examples.
