### ISSUE TITLE
Variant pages should not link to phenotypes

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#189]
https://beta.monarchinitiative.org/variant/ClinVarVariant:12644

For instance, the 56 phenotypes shown here relate to the DISEASE and not to this particular variant.

**Comment by kshefchek** [comment]
@mellybelly @cmungall @pnrobinson at some point we should review all of our database joins, many of these were written years ago and have not been reviewed for our updated target audience

**Comment by kshefchek** [comment]
these should be gone now, see https://beta.monarchinitiative.org/variant/ClinVarVariant:12644

**Comment by kshefchek** [comment]
I think I jumped the gun on this, can we discuss what we should be inferring across phenotype-disease associations, specifically genes and variants.  Should we filter in/out based on frequency qualifiers?
