### ISSUE TITLE
Literature node pages needed

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#19]
Even if they're sparse, I'd like the literature node pages to exist. This is important for integration with Hippo too.

**Comment by monicacecilia** [comment]
Could you please provide additional information for this issue? 
For instance, 
- a mock up (hand-drawn ok!) of what these pages should look like?
- could you offer a list of the types of information available in these pages (if more than just PMIDs, etc.)?
- what should users be able to do with the data? e.g. export list of publications? (if applicable), etc. 

(and for personal reference, when/how do users get to this information?)

**Comment by jmcmurry** [comment]
The current pages (while not integrated into the site) are reachable if you hard code the URL. An example of one is [here](https://monarchinitiative.org/literature/PMID:21248748). It needs to be reconfigured to show that the publication is the source of the association between two things, rather than just a list of the implicated entities.

**Comment by DoctorBud** [comment]
This has been implemented for quite a while, although we are calling them 'Publications', and they are treated like proper nodes in the knowledge graph. For example, the Publications association with Marfan Syndrome: https://beta.monarchinitiative.org/disease/MONDO:0007947#publication

and a particular Publication: https://beta.monarchinitiative.org/publication/PMID:17680538
