### ISSUE TITLE
UDP/Patient pages on the new site

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#199]
Should we be moving our UDP patient pages to the new site?  For example,
https://monarchinitiative.org/case/:MONARCH:c000017

https://github.com/monarch-initiative/operations/issues/113

**Comment by monicacecilia** [comment]
@mellybelly says: we should indeed migrate these pages over to the new website. To do so,
- [ ] First: we should port these pages over in their current state. 
   - [ ] We need to update the data from UDP. (@kshefchek - [UDP API](https://udplims-collab.nhgri.nih.gov) is still down)
   - [ ] Give the pages a ___minor___ face lift, adding an icon for 'patient pages,' other things? @mellybelly please comment
- After v1.0 release, we should work on improving how we offer patient pages throughout the site by: 
   - Adding new pages from UDN, 
   - Adding the ones from [MyGene2](https://mygene2.org/MyGene2/)
   - Maybe also adding new ones from Genomics England
   - Maybe also adding new ones from [SolveRD](http://solve-rd.eu/)

**Comment by monicacecilia** [comment]
@kshefchek How are these pages generated? I imagine this is not static, we're pulling the patient pages. -- would you be able to please point @iimpulse in the right direction to look at including these pages in beta?

**Comment by kshefchek** [comment]
this would be driven by the biolink endpoints starting with 'case', for example:

https://api.monarchinitiative.org/api/bioentity/case/%3AMONARCH%3Ac000017/phenotypes?rows=100&facet=false&unselect_evidence=false&exclude_automatic_assertions=false&fetch_objects=false&use_compact_associations=false

It's odd that these ID's are indexed as :MONARCH:{id}, for example, :MONARCH:c000017.  Given our curie map that should resolve to https://monarchinitiative.org/MONARCH:c000017, which doesn't resolve, but https://monarchinitiative.org/:MONARCH:c000017 does

**Comment by kshefchek** [comment]
see beta.monarchinitiative.org/MONARCH:c000017

**Comment by monicacecilia** [comment]
@kshefchek, 
- does the current page satisfy all of @mellybelly's requests (listed [above](https://github.com/monarch-initiative/monarch-ui/issues/199#issuecomment-530144842))? 
- I see that the new page does not include the ability to download phenopackets, phenotypes and variants. Do we have plans to update this? Or did you and Melissa had a discussion about these and decided to do away with them?

**Comment by kshefchek** [comment]
> does the current page satisfy all of @mellybelly's requests
Nope, none of these boxes can be checked at the moment - minor facelift is subjective, but we do not have a special icon for patient pages (@jmcmurry ?)

> I see that the new page does not include the ability to download phenopackets, phenotypes and variants. Do we have plans to update this? Or did you and Melissa had a discussion about these and decided to do away with them?
The legacy site exports a very old version of phenopackets on patient pages, we also have tsv download buttons on every table.  The new UI does not have either of these, but we should plan for them (especially the tsv's are useful)
