### ISSUE TITLE
 Filter button itself shouldn't be multiselect 

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/monarch-ui#2]
- [x] Button should be labeled "All" when nothing selected or the name of the filter
- [ ] button shouldn't allow multi-selection
- [ ] drop-down filter shouldn't overlap results if at all possible

From https://github.com/monarch-initiative/monarch-ui/issues/1#issuecomment-424805051

**Comment by pnrobinson** [comment]
@monicacecilia Is this issue still relevant? I do not understand what the action item is? Please close or provide details about what needs to be done.

**Comment by nathandunn** [comment]
I think that it was an awkward filter to have this me a multi-select (think of the way Amazon does this) versus a single select: 

![image](https://user-images.githubusercontent.com/751274/60972622-77071080-a2db-11e9-894d-6d84a2d3efcf.png)

I wouldn't bother for a 1.0 release, but it would be better to convert it to a single select at some point.
