### ISSUE TITLE
Glossary needs to be completed

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-ui#203]
https://docs.google.com/spreadsheets/d/1B0f1rE5SAkPfOsE0M22QWTDx-z3_gkLvJn6AyVltco0/edit#gid=0 has a list of acronyms/abbreviations/resource names that we use in the NAR paper. This needs to become a file in GitHub (ASAP, so we can include its URL in the NAR paper). Julie suggested putting it in this repo, in a new "docs" directory.

There are a lot of things that need to be finished in https://docs.google.com/spreadsheets/d/1B0f1rE5SAkPfOsE0M22QWTDx-z3_gkLvJn6AyVltco0/edit#gid=0 -- acronyms need to be spelled out, "deleted" rows need to be removed, URLs need to be added--but that could take longer, and we need a stable GitHub URL in the next day or two.

Also to do: merge in relevant terms from https://docs.google.com/document/d/1tqjmrtJtii_Qa4OIElANm6Fcy3Ay8If2Vc2pPzjJ_2Y/edit

-- Lauren, Melissa and Moni said you are willing to work on this. Thank you!

**Comment by nlharris** [comment]
@monicacecilia: I couldn't find a GitHub account for Lauren.

**Comment by nlharris** [comment]
@jmcmurry merged the two glossaries: https://docs.google.com/spreadsheets/d/1B0f1rE5SAkPfOsE0M22QWTDx-z3_gkLvJn6AyVltco0/edit#gid=1364170751

**Comment by monicacecilia** [comment]
Added @jmcmurry's page in #205

**Comment by nlharris** [comment]
I don't think we should close this issue, since the glossary still needs a lot of info filled in. It's at https://github.com/monarch-initiative/monarch-ui/blob/master/src/views/glossary.md

**Comment by monicacecilia** [comment]
@nlharris - ok. please feel free to update as you collect more information.

**Comment by jmcmurry** [comment]
Accordingly and for convenience, curation of the living document is not done here but rather [here](https://docs.google.com/spreadsheets/d/1B0f1rE5SAkPfOsE0M22QWTDx-z3_gkLvJn6AyVltco0/edit#gid=1364170751). Note that Column D is the formula-driven concatenation of content that can be wholesale pasted into the .md
