### ISSUE TITLE
Text annotator matches should link to monarch pages in some cases

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#209]
The text annotator widget provides a drop down for matching terms.  Some of these terms should link to monarch pages.  I'm not exactly sure how to go about this, but a ID prefix filter could be a quick way to achieve this (HP, MONDO, MP, etc)

**Comment by mellybelly** [comment]
it might be nice to show which ones link to monarch pages vs. not also.

**Comment by monicacecilia** [comment]
Optional: 
- For Text Annotator output: 
   - term | ID | position in text.
   - one row per annotation, per term.
   - download XML or JSON, to begin with.

**Comment by jmcmurry** [comment]
- Remove unlinked recognized terms from the rendered version in the UI
- Include them in the download
- Include explanatory text: "The downloaded version of these annotations contains additional recognized terms that do not have corresponding web pages in Monarch."

**Comment by jen-martin** [comment]
Any suggestions for styling the new explanatory text? @jmcmurry 
![image](https://user-images.githubusercontent.com/67020823/117076633-8c88ce00-aceb-11eb-85f3-8c01bff6e2af.png)

**Comment by jmcmurry** [comment]
How about this: Lets incorporate a subtle info icon above each of the 3 buttons.
![image](https://user-images.githubusercontent.com/3658863/117080303-69ade800-acf2-11eb-80d0-caaebcd01dee.png)

On hover over any part of the button, or upon click of the corresponding info icon

- **Back:** Edit the input text
- **Download annotations:** Download a spreadsheet of recognized ontology terms and the corresponding input string with which they were matched. This will include terms that were recognized but do not have a corresponding web page in Monarch.
- **Analyze phenotypes:** Search for diseases and genes that are phenotypically similar to the list of phenotypes recognized in this text. You will be able to edit the list before running the search.
