### ISSUE TITLE
Use vectorised Monarch Logo on the top menu bar

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-ui#212]
This spoils slightly an otherwise super beautiful beta ui :) 

![image](https://user-images.githubusercontent.com/7070631/65618118-af062180-dfb5-11e9-949c-e0a351ec3a3e.png)

**Comment by monicacecilia** [comment]
@iimpulse - not urgent, but a nice-to-have.

**Comment by monicacecilia** [comment]
@iimpulse - the vector images for Monarch logos can be found at https://github.com/jmcmurry/closed-illustrations/tree/master/logos/monarch-logos

(I think you should have access, but if not, please ask @jmcmurry to let you in).
