### ISSUE TITLE
Add 'Beta' and 'Go Back to Main Site' buttons to our sites as appropriate.

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#215]
Obsolete.

~~- [ ] Create a button that allows users to switch between the production and beta websites.~~
   ~~- Would ideally lead the user to a page with the "same" data they are currently seeing on the production site  but over the Beta site, and vice versa. E.g. A 'toggle' button for page in the production site https://monarchinitiative.org/disease/MONDO%3A0011213 takes you to this page https://beta.monarchinitiative.org/disease/MONDO:0011213 in the Beta site.~~
  ~~- An earlier / less complex (?) version of this button could direct users to the 'other' website's Home Page.~~
~~- [ ] Make the 'toggle' option persistent in all pages on both websites.~~
~~- Please feel free to explore other options for text:~~ 
   ~~- 'Toggle to Production' ??~~
   ~~- ' Back to production' ?? ~~
  ~~ - etc.~~

**Comment by iimpulse** [comment]
Kind of tough, not sure if its a great idea, do we know the mappings between the two sites url wise?

Would rather just full commit at some point.

**Comment by monicacecilia** [comment]
Thanks @iimpulse. While preparing the submission for NAR, we held a discussion with the leadership and decided that this would be the best course of action right now. 

At the very least, we should start with a button on the home page on both sites. This would involve you adding one to beat, and @kshefchek adding one to production.

**Comment by monicacecilia** [comment]
- Dear @kshefchek, this is a kind reminder to please:
  - [ ] Update the Monarch production site to include a ‘_Try our Beta version_’ button with link to the Beta website.
- Dear @iimpulse, this is a kind reminder to please:
  -  [ ] Update Home Page on Beta website to also include the ‘_Beta_’ button.
  - [ ] Add a persistent ‘_Go Back To Main Site_’ button or box with text, located either below or next to the current ‘Beta’ button. In this context, 'persistent' means that this button/box should appear in all pages. This button / box should link to the Home Page in the production site.

**Comment by kshefchek** [comment]
this has been added to both the beta and legacy apps, although we're not linking to exact pages beyond the homepage.  sounds like this is sufficient so will close this ticket.
