### ISSUE TITLE
Update latest blog posts on old monarchinitiative.org home page

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-ui#220]
Note that this is about the OLD (but still the visible default) site. I am adding this ticket here because I'm not sure anyone looks at the issues in monarch-app.

The (old) home page has a section called "News and Events" that lists the most recent 4 blog posts. The latest one it has is June 10.
<img width="525" alt="Screen Shot 2019-10-04 at 11 45 41 AM" src="https://user-images.githubusercontent.com/348704/66231975-aa6bf800-e69c-11e9-8447-9d2ba9787477.png">
Please replace those 4 old posts with the 4 latest ones from https://medium.com/@MonarchInit:
https://medium.com/@MonarchInit/new-release-of-mondo-disease-ontology-9a48521353e3
https://medium.com/@MonarchInit/melissa-haendel-envisions-a-sustainable-data-trust-86794c7835c4
https://medium.com/@MonarchInit/micronutrients-in-the-semantic-landscape-perspectives-from-a-nutrition-grad-student-b0b70b6e6ae5
https://medium.com/@MonarchInit/https-medium-com-monarchinit-nlm-talk-data-reusability-in-translational-research-7046aa229ccf

Thanks!

**Comment by kshefchek** [comment]
i've updated the site, thanks for the reminder!
