### ISSUE TITLE
Redundant disease annotations for a gene

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-ui#225]
E.g

![image](https://user-images.githubusercontent.com/50745/67609338-12b07580-f741-11e9-99b1-6fb1663147b4.png)

I find the display confusing. I don't see how OMIM contributed to the generic association as OMIM IDs are only for specific diseases.

I think this is all simpler if

 1. We only trust OMIM and Orphanet for mendelian
 2. We have a simple redundancy filtering step where we push down an Orphanet if it is concordant with OMIM (and keep this as provenance)

**Comment by pnrobinson** [comment]
according to Orphanet's logic this is correct. PIBF1 mutations cause Joubert syndrome full stop (the 33 is not important clinically). 
However, for users, this is probably confusing and we should not inherit the causal genes up the Ordo hierarchy, I agree

**Comment by kshefchek** [comment]
https://kshefchek.github.io/monarch-ui/gene/HGNC:23352#causal-disease

**Comment by monicacecilia** [comment]
Thanks. Yes, this is already on our radar - and @kshefchek has a clearer display for this information on a branch that was just merged 2 days go. I'm going to close this ticket in favour of all the changes adopted in #224.
