### ISSUE TITLE
Duplicated Coriell models

### ISSUE THREAD

**Issue by julesjacobsen** [monarch-initiative/monarch-ui#227]
https://beta.monarchinitiative.org/gene/HGNC:3603#model shows 8 models, however they are duplicates. e.g. 

NIGMS-GM21943 | derives_from | affected male proband with Fibrillin 1 |   | Coriell | Coriell:GM21943
-- | -- | -- | -- | -- | --

is duplicated by the row underneath. The others in the top set with the Coriell links are duplicated in the 'affected male/femal proband with Fibrillin 1' rows.

The final 4 are duplicated in the Case tab:
https://beta.monarchinitiative.org/gene/HGNC:3603#case

Could be that the 'Model' tab shouldn't be showing human cases anyway, give these are represented in the 'Cases' and 'Genotypes'?

**Comment by kshefchek** [comment]
Since the source is a cell line: https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM21938, I've removed the duplicate genotype and cases, unless Coriell provides those identifiers (occasionally we get dbSNP individual xrefs from them.

**Comment by julesjacobsen** [comment]
The models look good now, but shouldn't these also be represented as cases too? The Coriell data are models derived from cases, aren't they? Or was this the source of the duplication?

**Comment by kshefchek** [comment]
The cases and genotypes are created based off the coriell record.  Given a cell line we create two blank/anonymous nodes for the case (person) and their genotype, assuming Coriell doesn't provide us with a dbSNP individual identifier.  So for a single record we were getting three rows on our data pages spread across the tabs.  We can reference the cell line or the case on our data pages.
