### ISSUE TITLE
No horizontal scroll bars

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#228]
Make sure we don't have horizontal scrolling
e.g https://beta.monarchinitiative.org/phenotype/HP:0000110#genotype

**Comment by kshefchek** [comment]
I had my browser zoomed, palm->face

**Comment by monicacecilia** [comment]
@kshefchek what does this mean? 
There are not genotype associations in the example listed above. What are we looking for here? 
Or perhaps Mike already worked on this and this needs to be closed?

**Comment by kshefchek** [comment]
We had a giant genotype label here, but based on some updates to our genotype-phenotype index it's gone.  We're no longer inferring genotype across coriell cell line-disease and disease-phenotype.  I think we can close.
