### ISSUE TITLE
UBE3A and Angelman syndrome

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#229]
## Describe the problem

UBE3A is listed three times under  noncausal gene associations. Any gene should only be listed once. Also, UBE3A is actually causal for Angelman. It is unclear to me that the other genes should be listed here also.

https://beta.monarchinitiative.org/publication/PMID:18701717#noncausal-gene

**Comment by kshefchek** [comment]
this isn't a bug, this is currently how we handle disease "groups" 

see
https://github.com/monarch-initiative/monarch-ui/issues/106
https://github.com/monarch-initiative/mondo/issues/685

**Comment by kshefchek** [comment]
The non causal associations are for angelman subtypes from Orphanet:

https://www.orpha.net/consor/cgi-bin/Disease_Genes.php?lng=EN&data_id=15680

We model "role in phenotype of' as non causal.

**Comment by pnrobinson** [comment]
Orphanet is not claiming that UBE3A is non-causal. These are different mechanisms by which UBE3A is inactivated. The lack of activity of this gene is the basic cause of Angelman syndrome. See for instance this https://www.angelman.org/what-is-as/medical-information/genetic-mechanisms-of-angelman-syndrome/

**Comment by pnrobinson** [comment]
I also do not understand what you mean with groups. One of the causal properties is a subclass of the other, correct?
