### ISSUE TITLE
cases for Angelman

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#230]
https://beta.monarchinitiative.org/publication/PMID:18701717#case

This page is showing 7 unlinked cases but there is no real case-level information or link. Does it make sense to show the information like this?
-Peter

**Comment by kshefchek** [comment]
https://beta.monarchinitiative.org/publication/PMID:18701717 no longer has a case tab, I suspect this was removed via some cypher clean up, @pnrobinson please reopen if you see any other issues on this page
