### ISSUE TITLE
Genotype vs Variant

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#231]
## Describe the problem

For Angelman syndrome (https://beta.monarchinitiative.org/publication/PMID:18701717#variant) we are showing both variants and genotypes, but these are artefacts of the original datasource and there is no true distinction to be made between them. The variants could also be interpreted as genotypes because there is no variation in the mode of inheritance!

**Comment by monicacecilia** [comment]
The 'variant' tab is now only showing variants.
