### ISSUE TITLE
Strange link

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#233]
If you start here:
https://beta.monarchinitiative.org/publication/PMID:18701717#phenotype
(i.e., on the page with 46  phenotype associations for ANgelman) and click on an HPO link (e.g. Hyperactivity), you land on this page: 
Angelman syndrome MONDO:0007113 (Redirected from OMIM:105830)
(https://beta.monarchinitiative.org/phenotype/HP:0000752), which right now at least is showing an entry for the disease Angelman syndrome rather than information about the HPO term

**Comment by kshefchek** [comment]
https://beta.monarchinitiative.org/publication/PMID:18701717#phenotype only shows 6 phenotypes, so I wonder if there is some weird routing issue happening here, it would be good to try to recreate this

**Comment by monicacecilia** [comment]
Thanks for reporting this, @pnrobinson 
The bug you reported has now been fixed. 
In your [example publication](https://beta.monarchinitiative.org/publication/PMID:18701717#phenotype), all listed phenotypes are associated with source data as appropriate, and include supporting evidence as appropriate.

**Comment by pnrobinson** [comment]
seems to be working!
