### ISSUE TITLE
Review gene expression associations, focus on odd link from genes to anatomical entities.

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#234]
The [page for the gene NDN HGNC:7675](https://beta.monarchinitiative.org/gene/HGNC:7675#anatomy) has a facet link to 'Anatomy,' which shows about 20 tissues, apparently because of an expressed relation. One of the tissues is "material anatomical entity", which is not that helpful. 
- We need to examine the associations between genes and anatomical entities.
- Also, it would be nicer to have a display showing the expression pattern of the gene with a bar chart rather than have a table with 20 entries. Gene expression is a relatively weak link between a gene and anatomy, and it is possible that a naive user would overinterpret the importance of this.

**Comment by monicacecilia** [comment]
See #236 ***Gene card for overview pages,*** for details about our plans to improve the display of gene information in Monarch.
