### ISSUE TITLE
Design a card with an overview of all genes associated with a disease

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#236]
Card for overview of Genes associated with a disease.

- [ ] Show chromosomal location 
- [ ] Show nature of association (causal, non-causal, etc)

In the fullness of time, would be good to also have a meaningful summary that incorporates gene functions, pathways, and / or interaction partners. This part is best broken out into a separate ticket later.

![image](https://user-images.githubusercontent.com/3658863/68094097-eb009200-fe51-11e9-942a-4e308ec7f150.png)

**Comment by pnrobinson** [comment]
Can we ingest the data from this database?
https://academic.oup.com/nar/article/48/D1/D977/5603224
This would allow a lot of really interesting bioinformatics

**Comment by monicacecilia** [comment]
Closing given comment on content (Chris) above.
