### ISSUE TITLE
R24 Aim 1.1: Enhance user navigation through the Monarch Portal (aka "progressive disclosure") / Disease overview page master plan

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#240]
There are separate issues for each of the cards:

- Phenotype monarch-initiative/monarch-ui#27 
- Genes monarch-initiative/monarch-ui#236 
- Models monarch-initiative/monarch-app#865 
- Description monarch-initiative/monarch-app#863 
- Related diseases monarch-initiative/monarch-ui#241 

![image](https://user-images.githubusercontent.com/3658863/68094788-b512dc00-fe58-11e9-9f5d-5e66ddab5e7d.png)

**Comment by monicacecilia** [comment]
The conversation turned away from progressive disclosure in early 2024. Other issues mentioned here are covered in https://github.com/monarch-initiative/monarch-app/issues/737
