### ISSUE TITLE
Update PhenIX entry

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#244]
(...) PhenIX is available here from Peter Robinson's group at Charité.

@julesjacobsen Is there a viable path to keeping Phenix in Exomiser or should we remove it?

If we retain, then s/Charité/JAX/

**Comment by julesjacobsen** [comment]
Not to  my knowledge - although there might be some code in Phenol to generate the N.out files? If there isn't then we'll heave to pronounce the PhenIX dead, unless Sebastian is willing to share how these are produced.

**Comment by pnrobinson** [comment]
What do the N.out files do again? At one point I had code for all of this and if the N.out files are the distrivutions then yes there is code in phenol for it.

**Comment by julesjacobsen** [comment]
Yes, these would contain the distributions e.g 1.out looks like this:

```
>100506658_100000.0
0.0-1E0
0.003-9.9581E-1
0.13-8.7177E-1
0.311-8.6985E-1
0.382-8.6852E-1
0.521-8.4004E-1
```

**Comment by monicacecilia** [comment]
The entry has been updated on the Beta website, to reflect Charitè and JAX. The PR has been merged and the changes will be reflected as soon as we re-build the app. I'm closing this ticket. Please be sure to re-visit your suggestions to update Phenol or Exomiser as appropriate in the corresponding repo. Thank youuuuus! :bowtie:
