### ISSUE TITLE
Feature the HPO UI more prominently

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#248]
HPO web should be a menu item and/or under a partners section on the homepage (this is probably more important than showing tweets).

**Comment by monicacecilia** [comment]
- Should there be a way to describe and point to all our ontologies? 
- Should there be a list of all our tools on the website, _on the website_? 
   - Search, Disease/Phenotype Explore, PhenoGrid, Text Annotator, Monarch Phenotype Profile Search, Monarch Tryptic Profile Comparer ....  (list from MI data call)
- Should we also have a page with details of the complete MI stack? Perhaps an updated version of [this "Monarch stack' Google document](https://docs.google.com/document/d/1Yt6WdEJB73m-EOhqT1I6ZSgQmo-7fhR8AH8tUlGFkJI/edit#heading=h.o33ybea27f3).

**Comment by pnrobinson** [comment]
A menu called Ontologies might be good -- we could have a section for core Monarch Ontologies, Ontologies that we contribute a lot too, and ontologies we contribute to once in a while; each ontology would be a menu item, and we separate the three categories with bars?

**Comment by justaddcoffee** [comment]
> A menu called Ontologies might be good -- we could have a section for core Monarch Ontologies, Ontologies that we contribute a lot too, and ontologies we contribute to once in a while; each ontology would be a menu item, and we separate the three categories with bars?

@monicacecilia If we do get a consumable JSON file with ontology info from Nico or someone, I possibly could have a go at automagically generating this core Monarch Ontology section @pnrobinson mentions here

**Comment by monicacecilia** [comment]
@justaddcoffee - agreed. That would be very useful. Let's keep an eye on #273 and work on doing this after we generate one such list (with Nico's help or otherwise). Thank you!

**Comment by monicacecilia** [comment]
There is now an 'Ontologies' submenu, available from the 'About' top-level menu item. The listed ontologies are divided into a group of 'ontologies maintained by Monarch' and a group of 'ontologies used by Monarch.' See https://beta.monarchinitiative.org/about/licensing#ontologies 

I like the idea of creating a 'partners' section in the front page, as well as other information described in #299. I don't think this should be a blocker to releasing, so I'll punt to the next milestone, in a new ticket and will close this discussion.
