### ISSUE TITLE
Option to see layperson equivalent of a phenotype profile

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#253]
This issue can be closed when there is a toggle that renders the phenotype profile list as a 'plain language' (aka layperson) or clinical view or both side-by-side. Additional (modest) research will need to be done to figure out how best to represent this to users since there's not always a 1-to-one mapping.

**Comment by kshefchek** [comment]
cc @pnrobinson (came up at IDG hackathon)
