### ISSUE TITLE
Update Phenogrid NPM reference.

### ISSUE THREAD

**Issue by iimpulse** [monarch-initiative/monarch-ui#254]
Dont forget to deploy phenogrid on NPM and change the reference.

Must reachout to IMCP, and ZFIN.

**Comment by kshefchek** [comment]
Fairly certain ZFIN does not use phenogrid

**Comment by monicacecilia** [comment]
@kshefchek - see email; please share details with IMPC.

**Comment by kshefchek** [comment]
@monicacecilia - done!

**Comment by monicacecilia** [comment]
Thank you!  You Da Bomb! :bowtie: 
I also sent out another ping to ZFIN - we'll see what they say.

**Comment by monicacecilia** [comment]
Update: 
- @kshefchek sent out instructions to IMPC, waiting to hear back.
- ZFIN responded - they are not using Phenogrid right now.

**Comment by monicacecilia** [comment]
@iimpulse please remember to reach out if you are ready. 
We should try to do this ASAP. Thanks!

**Comment by monicacecilia** [comment]
Let's update now. 
Let legacy API running so it doesn't break for those who haven't done the changes. 
Let's reach out and remind them.

**Comment by monicacecilia** [comment]
ping!

**Comment by monicacecilia** [comment]
:bowtie:
