### ISSUE TITLE
Make human gene names top search result

### ISSUE THREAD

**Issue by Antonialock** [monarch-initiative/monarch-ui#260]
I think it would be nice if human gene names appeared at the top in the simple search box results drop down - it is unnecessarily clunky and clicky to have to go into the full results list for what I presume is the organism of most interest.

Eg here I am looking for the human GNB1 but it is not among the top 10 results

<img width="282" alt="Screenshot 2020-01-17 at 12 29 18" src="https://user-images.githubusercontent.com/12727506/72612830-c29f1480-3925-11ea-9055-dde2df6b6e82.png">

Hope you will consider this suggestion, thanks!

**Comment by kshefchek** [comment]
On our beta site (https://beta.monarchinitiative.org/), we rank by the number of edges connected to a gene (secondary to the lexical match), so typically mouse or human will show up first.  For the gnb1 example human shows up first.  We'll be updating our production site monarchinitiative.org with our new app in the coming months.

**Comment by Antonialock** [comment]
that's a cool solution, great
