### ISSUE TITLE
Issue parsing biolink fields on data tables

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#261]
The relation field and a few others are not properly parsing the biolink json, not sure if this from a recent change in biolink or the ui code, for example: https://beta.monarchinitiative.org/disease/MONDO:0007947

Could also be from bumping the boostrap-vue library from 2.0 to 2.2?

**Comment by kshefchek** [comment]
also affects search https://beta.monarchinitiative.org/search/EPHB4, which makes me think it's a bootstrap-vue version issue

**Comment by monicacecilia** [comment]
Closing. This has been fixed.
