### ISSUE TITLE
Improve list of ontology terms on about license page

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/monarch-ui#273]
The list of ontologies on the [about license page](https://github.com/monarch-initiative/monarch-ui/blob/master/src/views/AboutLicensing.md) is basically [this list](https://github.com/monarch-initiative/scigraph-docker/blob/master/conf/data/monarchLoadConfiguration.yaml.tmpl#L70). I actually did this, but it's possibly not the list of ontologies we want to display here. 

I think (but could be wrong) that we actually want a list of ontologies that Monarch produces, not those that we ingest.

Ideally, somewhere in the Monarch software stack we'd generate a consumable (json?) file with a list of ontologies which we produce, along with license info. Or, failing that, if someone has a list of these, I'll manually update the page for now.

@monicacecilia @jmcmurry I await your license-y ontology wisdom

**Comment by monicacecilia** [comment]
I am hoping we can use @matentzn's expertise here.  We had already connected with him on that google doc that Julie started. 

You are correct, @justaddcoffee. We do not want all the ~40 ontologies in the Monarch knowledgebase. I asked Nico to please prepare a list of _those ontologies that we consider maintained by monarch, plus a handful of the most "important ones" (e.g., GO)_. He is working on it and may be able to update next week.

Let's review together and decide whether that's the best course of action. 

If others have valuable input, please chip in.

**Comment by justaddcoffee** [comment]
+1 thx @monicacecilia

**Comment by justaddcoffee** [comment]
Nico categorizes ontologies into these two (overlapping) groups: 

Core ontologies: `"mondo","hp","upheno","sepio","geno","ecto","maxo"`
Key ontologies: `"bfo","caro","chebi","cl","clo","eco","fao", "faldo","pco","xco","foaf","dc","oban","iao",
"pw", "ero","fbbt","go","hsapdv","mondo","mpath","nbo","ncbitaxon","ncit","oba","pato","po","ro","so","stato",  "uberon","vt","wbbt","zfa"`

Which group do we want to display license info for? Or could do the union

**Comment by monicacecilia** [comment]
@justaddcoffee I would like to see both of these, please. I asked Nico to please prepare the lists that way.

(if others have stronger, different opinions, I'm sure they'll come down raining on us about it 😉)

**Comment by matentzn** [comment]
Wait, they should not be overlapping - copy paste error - please remove all the ontologies from the key section if they already appear in the core section. Sorry!

**Comment by justaddcoffee** [comment]
@matentzn No problem Nico! In that case we have these two groups I think - please confirm:

```
Core ontologies: ['ecto', 'geno', 'hp', 'maxo', 'mondo', 'sepio', 'upheno']
Key ontologies: ['bfo', 'caro', 'chebi', 'cl', 'clo', 'dc', 'eco', 'ero', 'faldo', 'fao', 'fbbt', 'foaf', 'go', 'hsapdv', 'iao', 'mpath', 'nbo', 'ncbitaxon', 'ncit', 'oba', 'oban', 'pato', 'pco', 'po', 'pw', 'ro', 'so', 'stato', 'uberon', 'vt', 'wbbt', 'xco', 'zfa']
```

**Comment by matentzn** [comment]
Thats it!

**Comment by nlharris** [comment]
I went searching for a list of ontologies created/maintained by Monarch--I couldn't find it on the monarch website, but then I found this issue!
Users may not think to pull up the licenses page (https://beta.monarchinitiative.org/about/licensing) to look for the list of ontologies--maybe consider making it a page and menu item of its own, since ontologies are such an important Monarch product. And in addition to linking to the home of each ontology, perhaps you might want to add a publication to reference for each ontology, to raise the chances of users citing us!
I can make this a new issue if that would be helpful.

**Comment by matentzn** [comment]
I think this is a great idea. If anyone tells me where this script that generates this overview now lives, I can easily adopt it to add a publication field behind it.

**Comment by justaddcoffee** [comment]
@matentzn @nlharris I made a [PR](https://github.com/monarch-initiative/monarch-ui/pull/294) for this, you can have a look [here](https://justaddcoffee.github.io/monarch-ui/)

Content needs some work, but you can either push to this PR or tell me what you want me to change

**Comment by matentzn** [comment]
AH ok you use the template now.. 

Check this:

http://obofoundry.org/registry/ontologies.yml

on the same level as id, you have `publications:`

for example:

```
publications:
  - id: http://www.ncbi.nlm.nih.gov/pubmed/25140222
```

I would simply iterate over the publication tag (if it exists, it does not always!), and then do something like 

- Basic Formal Ontology : CC-BY License (cite1, cite2, cite3)

**Comment by nlharris** [comment]
I created a new issue #295 for adding the publication field, since that seems somewhat out of the scope of this ticket.
If that was the wrong thing to do, feel free to close that ticket and continue the discussion here. 😀
