### ISSUE TITLE
not possible to add phenotypes to build a profile?

### ISSUE THREAD

**Issue by realmarcin** [monarch-initiative/monarch-ui#276]
I can find phenotypes of interest via this search but there seems to be no way to add them to a 'profile'?

**Comment by kshefchek** [comment]
currently the only way to build a profile and perform operations on it is to use: https://beta.monarchinitiative.org/analyze/phenotypes 
or
https://beta.monarchinitiative.org/tools/text-annotate (then select analyze phenotypes)

although there have been discussions of other ways to do this (building up a profile as you navigate around the site and then submitting it for some analysis)
