### ISSUE TITLE
Add a download feature for Association Table and Phenogrid Table data

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#278]
Throughout the UI we need ways for users to get their hands on the data.

Specifically:
- [ ] Association data tables
- [ ]  Phenogrid table data @deepakunni3, @kshefchek, that includes the fields on the current version of the table, and to also include ‘most informative phenotype'. Previous iterations long ago had a list of matching phenotypes for every result, but I don't think we care about that here. That's ultimately the job of the triptych.

**Comment by kshefchek** [comment]
Depends on https://github.com/biolink/biolink-api/issues/77, https://github.com/biolink/biolink-api/issues/348

**Comment by monicacecilia** [comment]
This has been completed. :bowtie:
