### ISSUE TITLE
Suggestion: add a link with a complete list of all Monarch tools on the "Other tools" pages

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-ui#279]
https://beta.monarchinitiative.org/tools/other-tools

Including widgets, HIPPO, LIRICAL and whatever else there is.

**Comment by justaddcoffee** [comment]
What did we decide about ExomeWalker and PhenIX? Keep or remove from this page?

**Comment by justaddcoffee** [comment]
Already have a LIRICAL blurb, I added a HIPPO blurb (#288). Anyone have any other tools? OwlSim maybe? Could link to [this](https://github.com/owlcollab/owltools/wiki/Owl-Sim) github repo

**Comment by justaddcoffee** [comment]
Looking through our repos and the site, some other tools we could put on this page: 

Phenogrid: https://github.com/monarch-initiative/phenogrid
Dipper: https://github.com/monarch-initiative/dipper
HpoCaseAnnotator: https://github.com/monarch-initiative/HpoCaseAnnotator
Kboom: https://github.com/monarch-initiative/kboom

**Comment by monicacecilia** [comment]
@justaddcoffee - 
We need to make sure to find the most updated link for Phenogrid. Things have changed quite a bit in the past 6 months. @iimpulse will know the best link to add here. 
I agree. Let's add the other three (Dipper, HPOCaseAnnotator, and Kboom). We'll also need blurbs with descriptions. Thank you!

**Comment by justaddcoffee** [comment]
Okay, I'll put a PR together, and @iimpulse, if there is a better link than https://github.com/monarch-initiative/phenogrid for phenogrid let me know

**Comment by monicacecilia** [comment]
This page has been updated. 
@iimpulse - where does Phenogrid live?

**Comment by justaddcoffee** [comment]
[Here's](https://github.com/monarch-initiative/monarch-ui/pull/292) the relevant PR

I'm using [this](https://github.com/monarch-initiative/phenogrid) as the home of Phenogrid at the moment

**Comment by monicacecilia** [comment]
Fixed with #292
