### ISSUE TITLE
Implement simple table view of evidence

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#28]
npm module issue.

What is needed: 
- [ ] Translating OBO Graphs into Dot/Graphviz. Details at https://github.com/cmungall/obographviz

See also https://github.com/monarch-initiative/dipper/issues/787#issue-467172874

**Comment by pnrobinson** [comment]
@cmungall @monicacecilia @iimpulse My recollection is that the graphviz tools are in C and need to be run by a wrapper. Is this something that will work out of the box with a Vue system?
I would also comment that there is limited utility in displaying evidence as a graph. This is ubergeeky and is likely to overcomplicate the display. I would vote for not doing this.

**Comment by kshefchek** [comment]
cc @mbrush
