### ISSUE TITLE
Broken links on tools page

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-ui#280]
https://beta.monarchinitiative.org/tools/other-tools

The following urls are broken (at least one mentioned multiple times):
http://owlsim.org/
http://compbio.charite.de/PhenIX/
http://compbio.charite.de/ExomeWalker/

**Comment by monicacecilia** [comment]
@kshefchek --> could I kindly ask for the correct link for OWLSIM? 
@pnrobinson @drseb --> could I kindly ask for the correct links to PhenIX and ExomeWalker?

**Comment by pnrobinson** [comment]
PhenIX and ExomeWalker are not being independently supported. They are now (more or less) part of Exomiser, although they cannot be run quite the same as in their original versions. At some point, we should reimplement ExomeWalker, but this is not a near priority.

**Comment by monicacecilia** [comment]
@pnrobinson - a million thanks for addressing this so quickly. 
Should we just remove the linkouts on this page, then? And add a note about these tools being 'part of' Exomiser? Or some more adequate blurb? 
See https://beta.monarchinitiative.org/tools/other-tools

**Comment by pnrobinson** [comment]
The simplest thing would be to remove the links!
After the new site is released, we can return to each of the sections and add back the "Sahnehäubchen" (https://commons.wikimedia.org/wiki/File:Becher_Kakao_mit_Sahneh%C3%A4ubchen.JPG)

**Comment by kshefchek** [comment]
unfortunately owlsim2 does not have a homepage

**Comment by monicacecilia** [comment]
Okie. Thank you both. So we shall remove ALL those links. 
I would love to drink some Sahnehäubchen!! ☕️

**Comment by monicacecilia** [comment]
Fixed in #288.
