### ISSUE TITLE
Do not show frequency and onset for inferred disease to phenotype associations

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#282]
I am not sure if it is a good idea to display phenotype associations for "middle nodes" in Mondo. 
In any case, it is incorrect to inherit the frequencies "up" the hierarchy.

For instance,
amino acid or protein metabolism disease with epilepsy
https://beta.monarchinitiative.org/disease/MONDO:0016399#phenotype

is noted to have as obligate:
branched-chain keto acid dehydrogenase kinase deficiency | Obligate |  

but the "Obligate" is coming from one of the descendents and does not apply to the entire group.

**Comment by kshefchek** [comment]
This is unfortunately how we've designed it, on a disease page with a subtype we show the associations of its descendants including onset and frequency

Eg on amino acid or protein metabolism disease with epilepsy, where branched-chain keto acid dehydrogenase kinase deficiency is a subtype, we show the whole association including the disease name:

Seizures | has phenotype | branched-chain keto acid dehydrogenase kinase deficiency | Obligate

(not saying you're wrong just explaining the history)

For the UI level fix, we should remove frequency and onset data for any inferred associations, which we can determine by checking if the object id is the same as the node id in the table code.

I think in general inferred disease data is not working well and this should part of a larger discussion.

**Comment by monicacecilia** [comment]
Tested in #284 and awaiting resolution on #258 (and consequently #181).

**Comment by kshefchek** [comment]
#284 only addresses the phenotype profile search whereas https://github.com/monarch-initiative/monarch-ui/issues/282#issue-560707695 is about our tables
