### ISSUE TITLE
don't use string non-causal

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-ui#283]
gene page shows counts for causal and non-causal but there are members of both

e.g
https://beta.monarchinitiative.org/gene/HGNC:10848#noncausal-disease

shows hopoprosencephaly, but shh is causal for this yes?

I think the 2nd category should just be correlated with or something like that

**Comment by kshefchek** [comment]
> shows hopoprosencephaly, but shh is causal for this yes?

I think it's because it's associated to an OMIMPS Id, where we default to contributes to condition.

I also dislike noncausal, and the splitting in general I'm not sure works well, but +1 to changing it to correlated or something else

**Comment by monicacecilia** [comment]
- #303 Partially addressed this, the rest will need to come from BioLink. 
- @kshefchek is working on it this week.
