### ISSUE TITLE
Update homepage logos.

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#297]
- [ ] The image with logos in the home page should be updated to remove the 'Charitè' logo and add the '[Ada Health](https://ada.com/)' one.

**Comment by iimpulse** [comment]
I agree with the all of this. But I think this should be pushed until after we release. No reason to cram features or enhancements in. Let me know what you think.

**Comment by monicacecilia** [comment]
Ok. That's a good compromise. Let's update the logos, then. 
Here's the other ticket for the rest: #299

**Comment by monicacecilia** [comment]
Fixed in #302
