### ISSUE TITLE
Update homepage: add image of the month, add partners, reduce 'twitter' and 'news' sections.

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#299]
Suggestions for improving the homepage (by @mellybelly and @kshefchek):
  - [x] add an image that represents a featured 'disease of the month' or similar, to be positioned immediately after the green stripe with the nodes-and-edges image (the one with the words "Connecting phenotypes to genotypes across species"). @jmcmurry may have image suggestions.
  - [x] create a section about 'Monarch partners' and prominently display HPO.
  - [x] reduce the prominence of 'news' and 'twitter' columns, moving them down in the page, and

**Comment by jmcmurry** [comment]
.@nicolevasilevsky. Nicole, can you please put together a list of diseases you think would be interested to highlight on the homepage? If you put the Mondo IDs in a text file, make a PR [here](https://github.com/monarch-initiative/monarch-ui/tree/master/public) (to the master branch). Thanks :)

@iimpulse From the MONDO IDs will pull the definition, the HPO associations (stratified by category). Obvs there will be more phenotypes than can be displayed. If you can wire up the [histopheno widget](https://github.com/monarch-initiative/monarch-ui/issues/27) for this that would be amazing, but just a list and a "..." to expand would be better than nothing.

Thanks!

**Comment by nicolevasilevsky** [comment]
@jmcmurry I added a list with 4 terms, is that enough?

**Comment by jmcmurry** [comment]
Yes, certainly for now. We could perhaps carousel them. Thanks
