### ISSUE TITLE
Fix broken links from Monarch 'Model' tab to model pages in FlyBase

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#301]
All the links from items listed in the 'Model' tabs in Monarch, that are pointing to FlyBase pages, are broken. 

For example, links to _D. melanogaster_ models associated with [this disease](https://beta.monarchinitiative.org/disease/MONDO:0007113#model), and this [publication](https://beta.monarchinitiative.org/publication/PMID:18701717#model), lead to warning pages stating "_No such path available: /sequence featurevariant/FlyBase:FBal#######_," like [this one](https://beta.monarchinitiative.org/sequence%20featurevariant/FlyBase:FBal0244600).

**Comment by kshefchek** [comment]
we need to adjust https://github.com/monarch-initiative/monarch-ui/blob/master/src/lib/CategoryMap.js#L10
