### ISSUE TITLE
genes and pathways

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#311]
For posttranslational protein phosphorylation, it is possible for a protein to be a target or to carry out the phosphorylation. We apparently are just saying "involved in". I suspect that these are mainly "is target of" relations. We should distinguish.

In any case, there is no meaningful relation between Marfan syndrome and protein phosphorylation

https://beta.monarchinitiative.org/disease/MONDO:0007947#pathway

**Comment by pnrobinson** [comment]
I also do not understand why we are pulling in so many pathways for Marfan from Reactome, here I just see

https://reactome.org/content/detail/R-HSA-265402 ( Extracellular matrix organization (Homo sapiens))

but I do not see Regulation of Insulin-like Growth Factor (IGF) transport and uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs). FBN1 is one of 124 molecules listed here
https://reactome.org/PathwayBrowser/#/R-HSA-381426&FLG=P35555&DTAB=MT
but this is not really a function of FBN1 itself AFAIK, this is a friend of a friend (of a friend). 

The Uniprot descriptions are probably more reliablee
https://www.uniprot.org/uniprot/P35555

**Comment by jmcmurry** [comment]
@cmungall and @pnrobinson agree this can and should be fixed short term. 
Longer term plan is to display phenologs and with better context (say something like "6 pathways have this gene in common")

This ticket is specifically to do with the Reactome annotation which is out of scope for Monarch.
We shouldn't use the "involved in" relation, rather we should use "participates in"
A single gene in common doesn't constitute pathway relevance.

We should include asserted D2Pathway relationships (from Mondo curation).

cc: @mellybelly

**Comment by kshefchek** [comment]
Moving to https://github.com/monarch-initiative/monarch-cypher-queries/issues/40 since this happens when caching from neo4j -> solr
