### ISSUE TITLE
ECO codes dont seem to link properly to concepts

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-ui#313]
## Describe the problem

ECO codes dont seem to link properly

## Expected behavior
Should link to ontology!

## To reproduce

https://beta.monarchinitiative.org/disease/MONDO:0007947#phenotype
unfold support for first phenotype
unfold evidence code
click on evidence code

## Screenshots

If applicable, add screenshots to help illustrate the problem.

## Additional context

Add any other context about the issue that you feel may be important. e.g. browser version, time of day.

**Comment by monicacecilia** [comment]
Re-tested. this has already been fixed. 
woohoo! 🎉
