### ISSUE TITLE
Ordering of columns in some of the UI data tables

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/monarch-ui#318]
Hi all.  The new website looks great!  A couple quick comments/suggestions concerning ordering of columns in data tables for some of the sections.
 
I started navigation using the suggested 'Marfan Syndrome' query, as many initial users will do.  When I get to the Disease page, I started clicking through the categories of information on the left. Where I get hung up is interpreting the semantics/meaning of the rows in the Pathway, Model, and Genotype tables.  I think these could be laid out so it is clearer what the table is asserting about Marfan syndrome.
 
- For the [**Pathway table**](https://monarchinitiative.org/disease/MONDO:0007947#pathway), I assume that the assertions being made are that each listed signaling pathway (e.g. Post-translational protein phosphorylation) is "involved in" Marfan syndrome (i.e. there are defects in the pathway that cause the disease, or disease phenotypes rely on these pathways in some way).  But the direction implied by the columns shown in the table are backward - such that a direct reading seems to assert that Marfan Syndrome is "involved in" these canonical signaling pathways - which seems odd.  
 
- The [**Model table**](https://monarchinitiative.org/disease/MONDO:0007947#model) has a similar issue - if we assume the subject of each row is Marfan Syndrome, a left to right reading of rows in the table is potentially confusing because the name of the relation is backwards (should be "is modeled by").  And here there is the additional issue here that the Species is in the first column.  
 
- The [**Genotype table**](https://monarchinitiative.org/disease/MONDO:0007947#genotype)  has a similar sources of confusion as described above (the relation is backward, and the first column is the Species). Additionally, the relationship here is about being a disease model - so it is confusing why these are not in the Model table.
  
I know most users will be able to intuit the meaning of rows in these tables, but I think it best to be as consistent and explicit as we can in how we present info.  A possible, simple, general solution is to always use the first three columns in these tables to hold the **subject**, **relation**, and **object** of the core assertion being made in this order -  and ensure that the relation is named in the right direction.  e.g. for the 'Model' tables, column 1 would hold the subject (Marfan syndrome), column 2 the relationship (is modeled by), and column 3 should hold the name of the model.  I think the 'Species' makes sense to put as column 4 - after the name of the model.  
 
Doing this would of course lead to an extra column for most tables (to explicitly hold the subject that will be the same in every row) - but there seems to be room for this.  And if we didn’t want to include it, I think it would still be ok as long as the first column and second column were always the relation and object of the core assertion,/association, and the direction of the relation is correct (left to right)
 
I have not been on UI calls so apologies if it's just me who sees this as problematic, or you have discussed these issues already.  But thought I’d call them out and make suggestions for addressing them if folks think others will experience similar confusion.

**Comment by kshefchek** [comment]
theres a long history here that I'm guessing is not documented anywhere, but I can summarize:

Given an entity X that is associated with Y:

Implementation 1:
 - Y is leftmost column, unless there is a taxon for Y, then it's taxon, Y, ...
 - We added an arrow on the relation field to designate the direction of the relation, [this was hardcoded](https://github.com/monarch-initiative/monarch-ui/blob/54fdc8/src/components/AssocTable.vue#L325) and a little hacky

Feedback for 1: Users didn't like the redundancy of including X or subclasses of X in every column

Implementation 2:
 - Y is leftmost column, followed by the relation, unless there is a taxon for Y, then it's taxon, Y, relation ...

Feedback for 2: Users wanted the tables to read more like a sentence and did not like the relation being so far to the right

Implementation 3 (current):
- Relation is the leftmost column, unless there is a taxon associated with Y

I personally do not like the current implementation and find it the most confusing of the above, especially when X is the object of the triple.  Hoping in v1.1 we can improve this in some way or get more user feedback to support keeping 3.

**Comment by mbrush** [comment]
I agree with you for the most part Kent. Seems like the approach that would best address the user feedback and our personal preferences is to always assume the entity the page is about is the **subject** (e.g. 'Marfan Syndrome' in my example) - so we don't need to represent it in the table explicitly (as it would be the same in every row).   Then the table would be structured as below: 

- **Column 1** be the **relation** (whose _direction should always be from left to right_ - as this is how users will naturally read the data in the rows.  So in the Genotype page example, we would use the relation 'has model' to link a subject Disease to an object Genotype (which is the inverse of the relation that is shown now - 'has role in modeling').  You could even incorporate an arrow of some sort in the column 1 label to make this more explicit -  e.g. `-Relation->`
- **Column 2** would be the **object** of the association/assertion.
- **Column 3** would hold a **taxon for the object** if one exists (I assume the taxon is always for the object, as the subject of a given Monarch page is always specific to a species).

Just my two cents . . . happy to weigh in if you all discuss this in the future.

**Comment by kshefchek** [comment]
I might be misintepretting, but this would require flipping the relation (if an inverse property exists), for example, 'has phenotype' would be swapped with 'phenotype of'.  Ideally this would happen farther upstream of the app code.

**Comment by kshefchek** [comment]
> Just my two cents . . . happy to weigh in if you all discuss this in the future.

your feedback is always appreciated! keep it coming!

**Comment by mbrush** [comment]
> I might be misinterpreting, but this would require flipping the relation (if an inverse property exists)

yes, it would. We would need to have names for the relation in both directions (even if in the underlying data it is only represented in one direction).   e.g. on the Phenotype table for the 'Marfan Syndrome' page `has_phenotype` is the relation name and 'phenotype1' is the object. On the Disease table for the 'phenotype1' page,  `phenotype_of` is the relation name and 'Marfan Syndrome' is the object.

This approach may require making up names for inverse relationships, in cases where a formal ontology property for an inverse relationship does not exist. This could of course  introduce a disconnect between the labels that a human user sees on the website and what a data wrangler finds in the API or back end database. But I think this approach makes for the best UI experience on the website.

**Comment by pnrobinson** [comment]
I would vote for a rethink of the design of the phenotypes page. There is not need to repeat the subject and the relation multiple times, especially since you need to scroll through about 5 pages to see all of the phenotypes. I would also doubt that very many users are going to be  sophisticated enough to think about the relation/inverse as Matt is describing. Wouldnt it be enough to have some text somewhere near the table saying what the relation is for all of the rows?

**Comment by mbrush** [comment]
Hi Peter - addressing a couple of your comments, where I feel i should to clarify my proposal. 
 
> I would also doubt that very many users are going to be sophisticated enough to think about the relation/inverse as Matt is describing
 
I don’t think my proposal would require additional sophistication on the part of users - quite the contrary.  The proposal means that a user would see an explicit statement in each row that is always read left-to-right , and the name of the provided relationship would be consistent with this direction.  To allow for this consistent left-to-right reading, we may have to use an inverse of the relation we currently show (i.e. where the current relation supports a right-to-left reading).  For example, to allow for a Disease to be the subject and a Model to be the object of a Disease-Model association, we would need to use the inverse of the 'has role in modeling' relation currently seen on the [Disease-Model](https://monarchinitiative.org/disease/MONDO:0007947#model) page.  
 
There are of course variations on this them of being explicit about association semantics that avoid the need to use inverse relations - such as not committing to the subject of a page always being in the first column of an association table. As long as we list the S, R, and O in each row, which entity goes in which slot is less important.

At the end of the day, my personal preference is to be as clear and explicit about the meaning of what each association states to be true - even if this means some extra text in the tables that is duplicated across rows. But that's is just me, and this may be at odds with others' preferences, and with many UI best principles.  If we committed to consistently including the subject, relation, and object in every row, there will be no confusion over what is being asserted. Users would just have to deal with the duplication by focusing on the column that holds the data of interest as they scroll down the rows in a table.  This is not the most elegant UI, but might be the most effective for our needs. Just my 2c - no offense will be taken to impassioned disagreement likely to follow!
 
---------------------------------------------
 
A related observation is that there are some association types such as Variant-Disease where the 'relation' column is essential simply for the reason that different relationships are possible (pathogenic_for and likely_pathogenic_for relations)

**Comment by pnrobinson** [comment]
Hi Matt,
I completely agree that if we keep the tables as they are that we should take up your suggestion.
I am saying though that Monarch UI is an outlier among offerings in this sphere and that if we look at our competition (you will know who I am thinking of), the layout is simpler, and it is easier to see everything at once. With the Monarch UI, you basically need to click through about 50 pages to see all of the information for a disease that has a substantial amount of variants/phenotypes etc. I am not good at UIs, but I think that at some point we need to do some user research to figure out how people are using / navigating the information!

**Comment by kshefchek** [comment]
via @matentzn Pages like https://monarchinitiative.org/gene/ZFIN:ZDB-GENE-980526-166#phenotype are hard to look through; it would be good if there was some way to drill down into the data ala ribbons, phenogrid, or simply filters on table columns; especially if you wanna get a sense like: what kind of phenotypes is this gene involved in?
