### ISSUE TITLE
Human CFTR does not show up when searching for cystic fibrosis

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#319]
I thought at first it was related to https://github.com/monarch-initiative/monarch-ui/pull/214, but it turns out this is because gene definitions are fetched on the client/browser by querying mygene, so these do not make it into solr.  Cystic fibrosis does not appear in the solr document at any other point (ie synonym), https://solr-dev.monarchinitiative.org/solr/search/select/?q=*:*&fq=id:%22HGNC:1884%22&wt=json

possible solutions:
1. ingest gene definitions in dipper
2. ingest gene definitions when loading solr search

**Comment by kshefchek** [comment]
Looking at this closer, it looks like we only index synonyms on the clique leader id, but not those on equivalent Ids, which have additional synonyms, see
https://api-dev.monarchinitiative.org/api/graph/edges/from/HGNC:1884?relationship_type=equivalentClass

If we were to index the synonyms from equivalent ids then we would get CFTR when searching for  cystic fibrosis.

Relocating this to the solr loader

**Comment by kshefchek** [comment]
Reopening on the UI side since this is still an issue, another example is BRCA1 and breast cancer

**Comment by kshefchek** [comment]
I added synonyms of equivalent terms to our search index with https://github.com/SciGraph/golr-loader/commit/ef14285e18f434721393e4027a62f9a24be98350

This adds labels that should help with this issue, for example:
CFTR: cystic fibrosis transmembrane conductance regulator

BRCA1: breast cancer type 1 susceptibility protein

However, this hasn't entirely helped

![cystic](https://user-images.githubusercontent.com/1467299/103374655-2292ba80-4aa6-11eb-9ca9-563eb38e4a63.png)
![brca1](https://user-images.githubusercontent.com/1467299/103374657-245c7e00-4aa6-11eb-9cc8-5540f4545c50.png)

**Comment by monicacecilia** [comment]
This issue was resolved.
