### ISSUE TITLE
Broken urls in ontologies.yml

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#322]
https://github.com/monarch-initiative/monarch-ui/blob/25ac10/public/ontologies.yml contains some broken urls to http://build.berkeleybop.org/, which according to @kltm has been sent out to pasture.  I don't think any of these make it on our site, but good to fix or remove altogether if they're vestigial.

**Comment by kltm** [comment]
`  integration_server: http://build.berkeleybop.org/view/GO`
could be replaced with
`  integration_server: http://build.geneontology.org`

**Comment by monicacecilia** [comment]
@kshefchek, is this low-hanging fruit @iimpulse could help with?

**Comment by kshefchek** [comment]
I'm not really familiar with the file and how it drives the ontologies page, looks like a lot of extraneous data is there.  My vote would be for us to remove anything not necessary to drive the page.

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/monarch-ui/pull/326
