### ISSUE TITLE
Link to OMIM is broken

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-ui#323]
See https://github.com/monarch-initiative/mondo/issues/1450

The new Monarch UI has 2 links to OMIM phenotypic series on this page: https://monarchinitiative.org/disease/MONDO:0015194

The one constructed as http://www.omim.org/phenotypicSeries/300751 does not work/; the one as https://www.omim.org/phenotypicSeries/PS300751 does.

**Comment by monicacecilia** [comment]
@kshefchek ping!

**Comment by kshefchek** [comment]
This is the current curie mapping:
'OMIMPS': 'http://www.omim.org/phenotypicSeries/' 

https://github.com/monarch-initiative/dipper/blob/master/dipper/curie_map.yaml#L76

In theory scigraph normalizes all of the various curie mappings from upstream ontologies, but looks like something has gone wrong here, or maybe the curie is stored as a string in Mondo for dbxref?  The short term solution is probably to hack something in, but not sure it won't break some other OMIMPS xref

**Comment by kshefchek** [comment]
Also, the last item of the xref list is OMIMPS:PS300751.  Long standing ticket to normalize the IRIs we use in dipper and mondo - https://github.com/monarch-initiative/mondo/issues/804

**Comment by kshefchek** [comment]
Want to note that this issue also affects other ID mappings where we differ with ontologies, for example: 'MESH': 'http://id.nlm.nih.gov/mesh/' 

What I'm doing is adding hacks into the UI code, which is not optimal but is the easiest way around it at the moment.
