### ISSUE TITLE
Orphanet links broken from GARD

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#325]
GARD forwards to https://monarchinitiative.org/disease/Orphanet:{id}, whereas we changed our Orphanet prefix to ORPHA in the new app.  It might be easiest to ask GARD to update their links, but theres also a case to be made that we should support URLs that resolved in our original app (for bookmarks etc).

**Comment by kshefchek** [comment]
GARD is currently undergoing a website redesign, so while they have added a task to the queue it may take some time to update.  I think in the meantime we should consider a redirect since 39% of our referral traffic comes from them.

**Comment by vincerubinetti** [comment]
This hack seems to no longer be needed. If I [go to GARD and search "marfan syndrome"](https://rarediseases.info.nih.gov/diseases/6975/marfan-syndrome), it links to `https://monarchinitiative.org/disease/OMIM:154700`. A few other random diseases I tested also conform to this.

Going to exclude this from the monarch UI 3.0.
