### ISSUE TITLE
Confusing directionality of relations

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-ui#328]
On disease pages, when you click on phenoes or genes, you see relations like "has phenotype", which makes sense. When on a phenotype page, gene pages like https://monarchinitiative.org/phenotype/HP:0002705#gene list the "has phenotype" relation, which is confusing; shouldn't the inverse be listed (has gene or whatever it is?)?

**Comment by kshefchek** [comment]
Dupe of #318, will add your comments ther
