### ISSUE TITLE
misleading synonym listing

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/monarch-ui#334]
From @maglott's comment: https://github.com/monarch-initiative/mondo/issues/1511#issuecomment-629181985

> The display from Monarch https://monarchinitiative.org/disease/MONDO:0009211 does not make any distinction between related synonyms and synonyms. This is thus confusing to anyone using the Monarch display (where MedGen is going to point our users) It is likely just me, but I have never understood the use of 'related synonym' . If it strictly means something like 'Did you know we also have a related term xxx, so consider using xxx instead?', then I think it should not be reported with the word synonym.

I agree with this; the current display makes it look like the list of terms are all alternative labels for the concept. I think either the synonym types should be shown, and for "related" even distinguished further from the others, or, only "exact" should be shown in the current form.

This seems like an easy fix.

**Comment by kshefchek** [comment]
@balhoff @maglott @nicolevasilevsky curious your thoughts on how this looks on https://kshefchek.github.io/monarch-ui/

I wonder if adding all synonym types is an overwhelming amount of text and only showing exact synonyms is the way to go

**Comment by maglott** [comment]
I compared https://kshefchek.github.io/monarch-ui/disease/MONDO:0009211 to https://monarchinitiative.org/disease/MONDO:0009211

The display represents the underlying data accurately, which is a great help.  
Thanks for being so responsive.

**Comment by balhoff** [comment]
Thanks Kent, I think that is an improvement.

**Comment by kshefchek** [comment]
great! for now we'll show these synonym types on disease pages, but the rest we'll only show exact synonyms - otherwise it gets pretty messy with gene syns

**Comment by nicolevasilevsky** [comment]
Sounds great, I agree, this is a big improvement! Thanks Kent!
