### ISSUE TITLE
add a disclaimer that Mondo is not up to date in Monarch

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-ui#341]
please point people to OLS to browse Mondo

thanks!

**Comment by monicacecilia** [comment]
@cmungall @kshefchek 
- If we were to add a disclaimer, I would recommend adding it to the page where we describe that Mondo is one of our sources (@cmungall, @nicolevasilevsky: would that be enough?)
- We do not list Mondo as a source in https://monarchinitiative.org/about/data-sources - @kshefchek - halp?!

**Comment by monicacecilia** [comment]
The latest version of the ontology is included in the monthly KG builds. This has been resolved.
