### ISSUE TITLE
Split between genotype and variant views can be confusing

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-ui#342]
compare:

 - https://monarchinitiative.org/phenotype/MP:0013433#variant
 - https://monarchinitiative.org/phenotype/MP:0013433#genotype

particularly w.r.t Cog6

on the genotype page we have:

![image](https://user-images.githubusercontent.com/50745/84462858-e7718c80-ac24-11ea-964b-167f281b04cc.png)

with a sole source of IMPC

on the variant page we have:

![image](https://user-images.githubusercontent.com/50745/84462920-18ea5800-ac25-11ea-84cc-091c5a172a57.png)

sources IMPC and MGI

Then under gene:

![image](https://user-images.githubusercontent.com/50745/84462981-3f0ff800-ac25-11ea-905c-d6493f18c1c1.png)

it's confusing for someone to figure out what is going on here. I think this is all the same data, it's just when we ingest from IMPC we get it at one level of granularity in the GENO hierarchy, and from MGI at another. (it's not actually clear that bringing in IMPC adds value)

**Comment by kshefchek** [comment]
@cmungall what would you like to see as an improvement?  I think one issue is we have two different IDs for the same genotypes, but this is because MGI mints genotype IDs downstream of the IMPC releases (although maybe that process has changed)

**Comment by monicacecilia** [comment]
This problem was solved with the updates of the past four years. Information is now displayed with headers that guide the users through the results tables.
