### ISSUE TITLE
Neighbors widget is broken for non-cliqueleaders

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#344]
Compare:
https://monarchinitiative.org/disease/ORPHA:443909

To:
https://monarchinitiative.org/disease/MONDO:0018630

Mondo is the reference identifier for diseases in monarch and when linking using another id space we forward to the correct mondo id.  However, it appears this breaks the neighbors widget.  The proper fix may need to come from biolink (ie calls to graph/neighbors always return the graph around the cliqueleader)

**Comment by monicacecilia** [comment]
@kshefchek - is this still being blocked by the API? Or is this something we can start looking into again?

**Comment by monicacecilia** [comment]
No longer a problem.
