### ISSUE TITLE
On sources page, Mouse Phenome Database has wrong logo

### ISSUE THREAD

**Issue by pepprseed** [monarch-initiative/monarch-ui#345]
Hi, on this page:  https://monarchinitiative.org/about/data-sources
The entry for Mouse Phenome Database is accompanied by the "Reactome" logo... seems incorrect.

![Clipboard01](https://user-images.githubusercontent.com/20974589/85444887-cbdd7e80-b560-11ea-88b7-b9742ddc66b9.gif)

thanks!  -steve

**Comment by kshefchek** [comment]
thanks for pointing this out @pepprseed! this is now fixed on https://monarchinitiative.org/about/data-sources - let us know if the logo needs any updating
