### ISSUE TITLE
Fix broken jbrowse link

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#346]
Currently the genome feature component links to broken jbrowse pages:

For example: https://monarchinitiative.org/gene/MGI:98297
links to: http://jbrowse.alliancegenome.org/jbrowse/index.html?data=data/Mus%20musculus&loc=5:28456815..28467256

Long term we'll want to boot up our own instance of jbrowse for monarch, but the meantime we should link the alliance version at https://www.alliancegenome.org/jbrowse/

**Comment by monicacecilia** [comment]
As of 2020-07-27, https://monarchinitiative.org/gene/MGI:98297  no longer links to that JBrowse location.
See screenshot below. 

![Screen Shot 2020-07-27 at 12 39 17 PM](https://user-images.githubusercontent.com/1714621/88584330-4db04400-d006-11ea-9a9f-7800b1141495.png)

**Comment by monicacecilia** [comment]
This is what that location looks like right now at AGR: 
https://www.alliancegenome.org/jbrowse/?data=data%2FMus%20musculus&tracks=Variants%2CAll%20Genes&highlight=&lookupSymbol=Shh&loc=5%3A28450678..28473253

**Comment by jen-martin** [comment]
> As of 2020-07-27, https://monarchinitiative.org/gene/MGI:98297 no longer links to that JBrowse location.
> See screenshot below.

This was fixed with [PR 351](https://github.com/monarch-initiative/monarch-ui/pull/351) but the larger issue of what to do when mygene fails to get coordinates for organisms in jbrowse still remains.
