### ISSUE TITLE
Phenotype page under About

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#348]
[Googling for an existing definition](https://www.google.com/search?q=Phenotype+profile) of a phenotype profile, I did not get far. We could address this on the site. I admit this definitions is somewhat awkward as it draws on so many inter related concepts all of which need to be understood somewhat simultaneously. I think it would be great if we had a static page for this, preferably under a new page /about/phenotypes. Best would be a definition of a phenotype, phenotype profile, followed by a description of what could be done with one, perhaps bringing in Phenopackets concept too.

"A phenotype is an observable trait, such as height, eye color, and blood type. Phenotypes arise from the complex interplay of genetic and environmental factors. A phenotype profile is a collection of phenotypes for an individual organism at a given time. In the case of a disease, the corresponding phenotypes are commonly referred to as signs and symptoms such as fever, hypertension, or joint laxity.

When clinicians observe a cluster of individuals with similar phenotype profiles that do not match any known disease, they may describe these features in a scientific paper. Monarch curators and others have systematically read such papers and have extracted structured representations of the corresponding phenotypes for each known rare disease; the phenotype terms in these gold standard profiles are from the Human Phenotype Ontology."

**Comment by kshefchek** [comment]
let's make this a markdown driven page (for other examples see https://github.com/monarch-initiative/monarch-ui/tree/master/src/views) and then new content can be added by anyone

**Comment by kshefchek** [comment]
fixed with #354
