### ISSUE TITLE
Some IMPC genotypes not searchable

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-ui#349]
I'm looking for the genotype in this association

```
:MONARCH_b6bd92712d6a0d26c80b a OBO:GENO_0000646 ;
    rdfs:label "Mir203<tm1(mirKO)Wtsi>/Mir203<+> [C57BL/6N-MARC-mirKO_ES_PuDtk_8C1-1] (male)" ;
    OBO:GENO_0000382 :MONARCH_b62a8021ea143629edb0 ;
    OBO:RO_0002200 OBO:MP_0000218,
        OBO:MP_0005564 .
```

If I do a search I don't seem to find this genotype:

![image](https://user-images.githubusercontent.com/50745/84461988-ac6e5980-ac22-11ea-9027-7089901f212c.png)

I assume this is a data bug somewhere, maybe dipper making a pattern not picked up by solr?

Note also another data issue in the search - not all genotypes have an in-taxon

**Comment by kshefchek** [comment]
this ticket needs a concrete action item - for now will move it to discussions
