### ISSUE TITLE
Pagination broken after applying taxon filter

### ISSUE THREAD

**Issue by jen-martin** [monarch-initiative/monarch-ui#350]
The pagination is broken (see images below) after applying the taxon filter in some cases. This seems to happen in cases where you deselect species but the total number of associations to display after deselecting is still more than 15.

To replicate:
1. Navigate to: https://monarchinitiative.org/gene/HGNC:10848#ortholog-phenotype
2. Click on Taxon Filter
3. De-select the first two items (Mus musculus and Danio rerio). The remaining item should be Drosophila melanogaster (which has 28 associations).
4. Click Apply and Close.

Page 1 of results. All 28 associations are shown on the page. Note that the pagination buttons are displayed at the bottom of the page.
![pagination-error1](https://user-images.githubusercontent.com/67020823/88441347-afce3680-cdc5-11ea-957b-7a08f986b746.png)

Page 2 of results. Note that this is the same as Page 1 of results.
![pagination-error2](https://user-images.githubusercontent.com/67020823/88441416-e5731f80-cdc5-11ea-9064-39df880ef9f2.png)

**Comment by kshefchek** [comment]
@jen-martin if you'd like to circle back to this - would be great to have it fixed!

**Comment by monicacecilia** [comment]
No longer a problem.
