### ISSUE TITLE
HelpDesk: suggestion to sort lists; else, make lists downloadable

### ISSUE THREAD

**Issue by RuslanBV** [monarch-initiative/monarch-ui#357]
**Please describe your question, suggestion, or concern.**
I had encountered problem while looking for and listing genes.
Example:
https://monarchinitiative.org/disease/MONDO:0021100#correlated-gene in this link tried to find gene as it is not alpahbetically listed it was not possible,
another solution is make list of gene downloadable so it could be used more efficiently.

Sincerely,
RB

**Comment by monicacecilia** [comment]
Lists are now downloadable.
