### ISSUE TITLE
Side bar menu association count is double the actual amount of associations

### ISSUE THREAD

**Issue by silorakdeveroveraar** [monarch-initiative/monarch-ui#372]
## Describe the problem

When on a gene page, the sidebar indicates that there are double amount of associations than shown when clicking on that section. When doing an api call for the associations, it returns the amount present in the section. Only seems to happen with associations in gene menus.

## Expected behavior

Show actual association count.

## To reproduce

Examples:
https://monarchinitiative.org/gene/HGNC:4851#interaction
https://monarchinitiative.org/gene/HGNC:9251#interaction

## Screenshots
![image](https://user-images.githubusercontent.com/22292701/99790474-78c62280-2b24-11eb-8fbc-86dbb484c523.png)
![image](https://user-images.githubusercontent.com/22292701/99790423-5f24db00-2b24-11eb-8197-0d9d48c44f77.png)

## Additional context
Firefox version 83

**Comment by kshefchek** [comment]
@silorakdeveroveraar thanks for the ticket! this is now fixed
