### ISSUE TITLE
Broken ensembl button on ensembl gene pages

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#376]
For example on https://monarchinitiative.org/gene/ENSEMBL:ENSG00000213121 the first button does nothing and the second links to Ensembl.  Note also the missing label for these, but that will need to be fixed upstream, it looks like ncRNA that do not get merged with HGNC don't have labels.

**Comment by jen-martin** [comment]
Does PR #403 solve the problem, or is there more to do on this ticket?

**Comment by jen-martin** [comment]
@kshefchek: I'm not seeing the missing label part of your comment. Can you clarify?

**Comment by monicacecilia** [comment]
(eek. I went trigger happy and merged #403 before I read you also wanted to have a look, @kshefchek. may I kindly ask you to please review and revert if you don't think it satisfies this ticket? Thank you, and sorry. :bowtie: )

**Comment by monicacecilia** [comment]
:bowtie:
