### ISSUE TITLE
Update Phenogrid

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#38]
Nice-to-haves for new UI (leftover from #26):
- [x] update to d3 v5
- [ ] ~~remove jquery UI code, replace with vanilla es6 or vue~~
- [ ] ~~2 panel-display~~
- [ ] ~~auto-update~~

**Comment by pnrobinson** [comment]
Is this issue distinct from https://github.com/monarch-initiative/monarch-ui/issues/104
Who is responsible for doing this?

**Comment by kshefchek** [comment]
We could consider closing this and reopening distinct tickets for the rest.  The biggest things were moving to d3 v5 and replacing the legacy rest endpoints with biolink which were fixed with https://github.com/monarch-initiative/phenogrid/pull/266

**Comment by monicacecilia** [comment]
@kshefchek I'm taking your suggestion and closing this issue in favor of #129, #130, and #131 for the work left to be done.
