### ISSUE TITLE
Improve css on search results view

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#381]
For example on https://monarchinitiative.org/search/marfan , the table rows blend in with the background, we should have this stand out from the background.  Wondering if something changed with https://github.com/monarch-initiative/monarch-ui/pull/361

**Comment by kshefchek** [comment]
@jen-martin could you take a look at this?

**Comment by monicacecilia** [comment]
@jen-martin - per our convo on Slack, here are some suggestions about color palettes that you could explore. 
- https://color.adobe.com/color%20theme_Logotipo%20INICIAIS-color-theme-17104812
- https://color.adobe.com/Olann-color-theme-17104653
- https://color.adobe.com/Color%20Theme%2013-color-theme-17104536
- https://color.adobe.com/My%20Color%20Theme-color-theme-17104444

**Comment by jen-martin** [comment]
How does this look?
![image](https://user-images.githubusercontent.com/67020823/112531278-9de1d080-8d64-11eb-8052-dd0fd7694402.png)

**Comment by jen-martin** [comment]
mobile view:
![image](https://user-images.githubusercontent.com/67020823/112531822-43953f80-8d65-11eb-9bd4-e807a3c88ee0.png)

**Comment by jmcmurry** [comment]
Looks good, thanks :)

**Comment by iimpulse** [comment]
I like it, whats up with the taxon stuff? Looks like alot of emptiness, maybe at mobile we remove either taxon or matching string column

**Comment by jen-martin** [comment]
There is a ticket to address the blank taxon field here in Mondo: https://github.com/monarch-initiative/mondo/issues/47

**Comment by jmcmurry** [comment]
Those issues on Taxon are longstanding for 5+ years; this can be closed without that fix

**Comment by monicacecilia** [comment]
Woooohooooo! :bowtie:
