### ISSUE TITLE
Mondo is out sync with Monarch - Rajab interstitial lung disease with brain calcifications, obsoleted 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-ui#382]
Please see this ticket: https://github.com/monarch-initiative/mondo/issues/2480

and comment:
https://github.com/monarch-initiative/mondo/issues/2480#issuecomment-747601527

**Comment by kshefchek** [comment]
we were doing some solr juggling to fix a pubmed bug - I know how to fix should be back in sync by tomorrow @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
great, thanks Kent!

cc @ValWood

**Comment by ValWood** [comment]
Thanks!

**Comment by kshefchek** [comment]
looks like this is fixed now, please reopen if something looks off
