### ISSUE TITLE
Broken MGI links on HP term page

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#384]
On 'abnormal nervous system morphology' https://beta.monarchinitiative.org/phenotype/HP:0012639

clicking **Other external resources** we have some broken links:
http://www.informatics.jax.org/accession/MGI:2173617
http://www.informatics.jax.org/accession/MGI:2173613

And also duplicate ids

Some of these are app issues, such as the IMPC ids and duplicates, but the IDs themselves are xrefs in the ontology:

HP:0012639 is equivalent to MP:0003632 which has these MGI ids as xrefs https://www.ebi.ac.uk/ols/ontologies/MP/terms?obo_id=MP:0003632

probably not much to be done about the ontology xrefs, we can submit an issue in the MP tracker

**Comment by monicacecilia** [comment]
Not just MGI, IMPC (obviously), and UMLS as well: 
- UMLS: http://linkedlifedata.com/resource/umls/id/C4022810
- IMPC: https://www.mousephenotype.org/data/genes/MGI:2173617, https://www.mousephenotype.org/data/genes/MGI:2173613

**Comment by monicacecilia** [comment]
This was fixed.
