### ISSUE TITLE
Need a better phenotype example

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/monarch-ui#4]
attn: @jmcmurry 

<img width="1238" alt="screen shot 2018-09-26 at 12 30 46 pm" src="https://user-images.githubusercontent.com/751274/46104365-119cc580-c188-11e8-8921-a5e292397cd4.png">

<img width="656" alt="screen shot 2018-09-26 at 12 31 29 pm" src="https://user-images.githubusercontent.com/751274/46104387-1ceff100-c188-11e8-870a-c4650aed7319.png">

**Comment by jmcmurry** [comment]
This is a valid phenotype https://monarchinitiative.org/phenotype/HP:0000003. Looks like Kent is on it.
