### ISSUE TITLE
Update list of publications

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#400]
Update the list of publications in https://monarchinitiative.org/documentation/publications to include 2020 and 2021.

There is not an automated collection. We can slurp details from myNCBI (https://www.ncbi.nlm.nih.gov/myncbi/) collections for Melissa, Chris, and Peter.

**Comment by monicacecilia** [comment]
Melissa's bibliography can be found here: https://www.ncbi.nlm.nih.gov/sites/myncbi/melissa.haendel.1/bibliography/43969963/public/?sort=date&direction=ascending

**Comment by jen-martin** [comment]
I've updated the pubs list for 2019-2021 using pubs found in pubmed for Melissa, Chris and Peter. See PR #402 and let me know if there are any more additions, or if a pub should be removed from the list.

**Comment by monicacecilia** [comment]
#402 was merged. We can close this now. :bowtie:
