### ISSUE TITLE
Authoritative linkout for 'Arachnodactyly' goes to wrong HPO term

### ISSUE THREAD

**Issue by jen-martin** [monarch-initiative/monarch-ui#414]
For '[Arachnodactyly](https://monarchinitiative.org/phenotype/HP:0001166)' ([https://monarchinitiative.org/phenotype/HP:0001166](https://monarchinitiative.org/phenotype/HP:0001166)) the authoritative HPO linkout in the External Resources box goes to HP:0100807 (one level above in the hierarchy).

**Comment by kshefchek** [comment]
this is a upheno 1 issue, as these two terms are equivalent there:

```
<owl:Class rdf:about="http://purl.obolibrary.org/obo/HP_0001166">
        <owl:equivalentClass rdf:resource="http://purl.obolibrary.org/obo/HP_0100807"/>
```

@matentzn any advice?

**Comment by matentzn** [comment]
Upheno 1 is very broken in many ways.. Its not been used for anything. Maybe we should up the priority of switching to upheno 2 again.

**Comment by monicacecilia** [comment]
This was fixed with uPheno2.
