### ISSUE TITLE
SciGraph text annotator is not returning categories for some terms

### ISSUE THREAD

**Issue by jen-martin** [monarch-initiative/monarch-ui#415]
- Some "high level" HPO terms are returned from SciGraph without categories. Example HPO terms: affected (HP:0032320), mild (HP:0012825), moderate (HP:0012826), severe (HP:0012828). 
- Terms from some ontologies do not return from SciGraph with categories. Examples (using the Text Annotator sample text): all RO and BFO terms

Example:
Using the Text Annotator sample text, biolink returns the following for "affected" in the original text:

`<span class=\"sciCrunchAnnotation\" data-sciGraph=\"Affected,HP:0032320,|acts upstream of or within,RO:0002264,|causally upstream of or within,RO:0002418,\">affected</span>`

(The category, such as "phenotype," "relation," etc., is missing from each of the terms.)

**Comment by monicacecilia** [comment]
No longer applicable. This technology was obsoleted.
