### ISSUE TITLE
ontology terms are resolved/displayed regardless of whether the category is correct or not

### ISSUE THREAD

**Issue by jen-martin** [monarch-initiative/monarch-ui#416]
Example 1: The relational ontology term RO:0002264 (acts upstream of or within) displays a phenotype page if it is mistakenly assigned to the phenotype category (https://monarchinitiative.org/phenotype/RO:0002264) or a disease page if it is mistakenly assigned to the disease category (https://monarchinitiative.org/disease/RO:0002264).

Example 2: The phenotype HP:0000365 (Hearing impairment) displays a gene page if it is mistakenly assigned to the gene category (https://monarchinitiative.org/phenotype/HP:0000365).

Note: This came up in the context of resolving links to Text Annotator terms that had broken links. It was noticed that links to ontology terms resolve regardless of what category is used in constructing the link.

**Comment by monicacecilia** [comment]
This was fixed in later versions of UI.
