### ISSUE TITLE
Semi-automate Featured Diseases carousel to show disease-of-the-month diseases

### ISSUE THREAD

**Issue by jen-martin** [monarch-initiative/monarch-ui#417]
- [x] Complete [Featured Diseases spreadsheet](https://docs.google.com/spreadsheets/d/1zuCNTgpn2zqxnN27hBiM6f8XNRriQLgJ9qIPwgGNwWs/edit#gid=1553753231) by adding disease-of-the-month diseases and Mondo IDs for the full year.
- [x] In the UI, update the carousel viewer to show relevant diseases-of-the-month based on the current month. The ["mondo_ids.txt" file](https://github.com/monarch-initiative/monarch-ui/blob/master/public/mondo_ids.txt) drives the carousel viewer diseases and will need to be edited to include the full list of diseases from the spreadsheet and the date in which to display the disease.
- [x] Update notes in [Readme](https://github.com/monarch-initiative/monarch-ui/blob/master/README.md#monarch-uipublic) to reflect changes to "mondo_ids.txt" file. 

See #399 for additional commentary.

**Comment by nicolevasilevsky** [comment]
@monicacecilia FYI, this is on my to-do list for late June.

**Comment by jen-martin** [comment]
fixed w/ PR #425
