### ISSUE TITLE
Update node-sass version

### ISSUE THREAD

**Issue by vincerubinetti** [monarch-initiative/monarch-ui#421]
Cloned the latest repo and tried running `npm run serve` and came across `ERROR in Cannot find module 'node-sass'`. The package probably needs to be added to the dependencies of dev dependencies. I'm guessing this was overlooked because the past devs all had it installed globally, perhaps?

**Comment by kshefchek** [comment]
it's in the devDependencies list, does it need to be moved to dependencies?

**Comment by vincerubinetti** [comment]
>  does it need to be moved to dependencies

Apologies, this was what I meant. But on further testing, simply upgrading to `"node-sass": "^4.14.1",` in dev dependencies fixed the issue. However I'm on a Windows computer, so that may be the issue. Perhaps you could confirm that the current package builds on your machine?

I can perhaps rename this issue to "update packages"?
