### ISSUE TITLE
Publications page -- duplicate Supporting Statements

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#427]
On this page, there is a citation that is listed with two sources. There is some hash key that we should not be showing to users, and other than than both lines look identical. Also, there should be some link to the assertion in ClinVar -- we should not just say "ClinVar" without providing the actual evidence trail.

MONARCH:b1aa340bd518fa3c0c7b | source | PMID:9101298 |   | ClinVar |  
-- | -- | -- | -- | -- | --
MONARCH:b101a93a4a49e2b47f1a | source | PMID:9101298 |   | ClinVar

I found this on this page

https://monarchinitiative.org/disease/MONDO:0017309#publication

**Comment by monicacecilia** [comment]
No longer applicable. This was fixed a while ago. Closing.
