### ISSUE TITLE
cell lines as models?

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#429]
Hi everybody,
I am wondering if we really want to list cell lines like this as models --
https://monarchinitiative.org/model/Coriell:GM21957
I am saying this because these cell lines are more like resources. Even if we could import the phenotype data, they would be more like case reports/phenopackets. They seem misplaced here.

**Comment by kshefchek** [comment]
@mbrush has a great write up here, as a background on the decision - https://github.com/monarch-initiative/dipper/issues/506

**Comment by monicacecilia** [comment]
We don't do this any more. :bowtie:
