### ISSUE TITLE
Show relationship type in G2D and other pages

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-ui#43]
Replaces #39 

The relationship type is important, especially for G2D

All pages should show relationship type. For G2D we want to list in order of priority, with pathogenic shown first.

**Comment by kshefchek** [comment]
Relationship type is unreliable until https://github.com/SciGraph/golr-loader/issues/35 is fixed

**Comment by DoctorBud** [comment]
We show relationship type now, although there are lots of arguments about how to do it, and whether we should apply the inverse if available. However, the basic issue this ticket is about is whether we are showing them, and we are. Closing this.

Examples:
- https://beta.monarchinitiative.org/disease/MONDO:0007947#gene
- https://beta.monarchinitiative.org/gene/HGNC:11180#variant

**Comment by cmungall** [comment]
Reopening.

My original requirement:

> For G2D we want to list in order of priority, with pathogenic shown first.

this doesn't seem to be the current behavior

**Comment by kshefchek** [comment]
relevant biolink tickets
https://github.com/biolink/biolink-api/issues/274
https://github.com/biolink/ontobio/issues/318

**Comment by monicacecilia** [comment]
Still to do here: identify and separate the association _causes condition_,  then, add to a separate table, or a different tab, differentiating this from the rest of the results.

Ideally, the API itself should sort things out. 

@jmcmurry said: in the causal relations table, would it be possible to omit the disease listing in the case of a leaf node? (is it possible to determine if something is a leaf node?)

It would be ideal to be able to inherit the functionality from legacy app. @kshefchek mentioned that in the legacy app we would have a boolean that would let you know if you were looking at a leaf node.

**Comment by kshefchek** [comment]
This support has been added to biolink:

##### causal associations
https://api-dev.monarchinitiative.org/api/bioentity/disease/MONDO:0007947/genes?rows=10&association_type=causal

##### non-causal associations (FBN2 will be gone in the next data release)
https://api-dev.monarchinitiative.org/api/bioentity/disease/MONDO:0007947/genes?rows=10&association_type=causal

##### all associations
https://api-dev.monarchinitiative.org/api/bioentity/disease/MONDO:0007947/genes?rows=10

(or add &association_type=both)

**Comment by jmcmurry** [comment]
Until this is fixed, I think we should remove Marfan as a suggested example to click on. Thoughts?

**Comment by pnrobinson** [comment]
I think we need to choose say 5 diseases and do a really deep dive. I am worried that we are going to show medically inaccurate data, and in general I think we are trusting some of our sources too much. I happen to know Marfan well but there is no reason to believe that it is special in this regard. In general we should avoid having relations that imply causality unless we really trust a source.

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/monarch-ui/pull/224
