### ISSUE TITLE
Do not pull in non-deleterious variants

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/monarch-ui#431]
On the page for Marfan syndrome, there are 1577 variants. Many of them are from dbSNP, including this one , which has no known clinical significance.

https://www.ncbi.nlm.nih.gov/snp/rs2017765?vertical_tab=true

Suggestions

* Come up with a strategy for which variants to import. For humans, I would suggest we limit to ClinVar pathogenic/likely pathogenic
* Document this strategy on the website!
* Remove variants like this which are not relevant

**Comment by kshefchek** [comment]
looks like these are coming from gwas catalog, would it make sense to split variants by causal and correlated, similar to genes?

**Comment by Wenwenzn** [comment]
Why are genes and diseases split by causal and correlated? Is this made by automatic methods or manual curation? 
What are the standards by which a gene or disease is regarded as causal or correlated?

**Comment by kshefchek** [comment]
The causal/correlated distinction is automated based on the source and strength of evidence.  Generally, causal gene to disease will come with primary support from OMIM or Orphanet, and correlated gene disease will come from gwas associations and associations with less evidence from OMIM, ClinVar, and Orphanet.

**Comment by pnrobinson** [comment]
@kshefchek  -- it would be useful to go over a few examples together! From what I am seeing, it looks as if we are pulling in irrelevant variants somehow, but I might just be misunderstanding something.

**Comment by kshefchek** [comment]
sorry different threads,

@pnrobinson the variant you're referring to comes from gwas catalog, but I don't see it being linked to [marfan syndrome](https://monarchinitiative.org/disease/MONDO:0007947#variant) on our site: https://monarchinitiative.org/variant/dbSNP:rs2017765, is it possible you found this on the FBN1 page?  In any case we are rewriting both our ingest and UI so there will be some opportunity to rethink all of this.

**Comment by monicacecilia** [comment]
Variants are now displayed differently. This issue was fixed. :bowtie:
