### ISSUE TITLE
Restructure search results from table to slug / card format

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#433]
The current table format for search results breaks with prevailing industry standards and it shows. It also has a number of disadvantages including:
1) misleading to users (conflation of results and association data)
2) lack of mobile responsiveness (multiple columns don't fit)
3) inability to alter displayed fields based on the kind of result (eg. taxon not really relevant for a chemical or publication)

If we move to more of a card / slug based format for results, it would be preferable. The matching string would be bold instead of a separate field. Note that for this to happen, a different font with an actual bold option would be necessary. I recommend Roboto. I prefer oswald font for curies.

![image](https://user-images.githubusercontent.com/3658863/125499449-769bebae-2626-47d3-aeed-2975af65e370.png)

**Comment by kshefchek** [comment]
@jmcmurry curious what you mean by "conflation of results and association data", there shouldn't be any association data in our search/autocomplete index so it would be good to track down where this coming from.

**Comment by jmcmurry** [comment]
We are not conflating computationally; however the table format for results makes it look more like association tables. Just trying to make them look more like search results 
Sent from my iPhone

**Comment by monicacecilia** [comment]
We do this now. :bowtie:
