### ISSUE TITLE
Show relevant qualifiers for D2P pages

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-ui#44]
E.g. https://alpha.monarchinitiative.org/disease/MONDO:0007947#phenotype

This should show frequency, onset, modifiers, etc

May need a biolink-api ticket - if added, then link to this project

Note HPO site doesn't show this yet either, eg. https://hpo.jax.org/app/browse/disease/OMIM:154700

**Comment by kshefchek** [comment]
Modifiers and inheritance are now in biolink, onset and frequency are in solr but are likely not in ontobio/biolink.

**Comment by kshefchek** [comment]
This is will available on api-dev once https://github.com/biolink/biolink-api/pull/288 is merged

**Comment by DoctorBud** [comment]
@cmungall I think this is fixed now:

- D2P: https://beta.monarchinitiative.org/disease/MONDO:0007669#phenotype
- P2D: https://beta.monarchinitiative.org/phenotype/HP:0001994#disease
