### ISSUE TITLE
Change pub node page language to "sources of curated associations"

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#441]
Given that the only pubs we have right now are association sources, the text should say "8 publications are sources of curated associations in Monarch"

![image](https://user-images.githubusercontent.com/3658863/128101568-b7addcfb-337e-4fe4-9fcb-b40c54783c77.png)

**Comment by kshefchek** [comment]
our literature index still contains inferred associations via different paths (eg publication is about a mouse that is a model of disease x), so saying curated might be too strong.

**Comment by jmcmurry** [comment]
Good point; What do you suggest?

**Comment by monicacecilia** [comment]
We do not currently have publications node pages. 🎺
