### ISSUE TITLE
Shift Publications html content to yaml

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#451]
among the pages that need to be yaml driven is publications
The ideal thing would be to use eutils to pull bibtex metadata from a PMID and / or DOI
The ideal thing that would be in yaml would therefore be the list of DOI/PMIDs; the rest would be dynamic. 
@kshefchek thoughts on this?

**Comment by monicacecilia** [comment]
It is now generated by a script. JSON format. :bowtie:
