### ISSUE TITLE
User in China unable to access monarchinitiative.org but can access beta.monarch

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-ui#456]
A user from China reached out and mentioned they cannot access https://monarchinitiative.org but can access https://beta.monarchinitiative.org/.  We're running production from netlify and beta from our OSU servers.  There appears to be some discussion on the netifly forums - https://answers.netlify.com/search?q=China

**Comment by vincerubinetti** [comment]
@falquaddoomi Was able to set up a proxy that should resolve the issue. Can we ask the user in China to test if the regular site works now.

**Comment by kshefchek** [comment]
@wenwenzn are you able to access https://monarchinitiative.org/ ?

**Comment by falquaddoomi** [comment]
I should clarify that the proxy running within Google Cloud is currently at https://monarch-proxy.ddns.net/. I think we'll have t add a [country-based redirect](https://docs.netlify.com/routing/redirects/redirect-options/#redirect-by-country-or-language) if we want users to be sent to that URL from monarchinitiative.org.

**Comment by Wenwenzn** [comment]
I still can not visit the website.

**Comment by vincerubinetti** [comment]
@Wenwenzn did you specifically try https://monarch-proxy.ddns.net/

**Comment by Wenwenzn** [comment]
OK, it works well. It seems to be the same as the beta version https://beta.monarchinitiative.org/ <https://beta.monarchinitiative.org/>.

**Comment by vincerubinetti** [comment]
@Wenwenzn Would you be able to help us by trying out these websites:

https://adage.greenelab.com
https://het.io
https://greenelab.github.io/preprint-similarity-search/

These are sites I've previously developed that are hosted on a free hosting service called GitHub Pages. I want to see if GitHub Pages is accessible in China. If it is, we can start using it for monarchinitiative.org and avoid the ugly monarch-proxy.ddns.net and other work-arounds all together.

**Comment by Wenwenzn** [comment]
These websites are all accessible in China.
