### ISSUE TITLE
add ribbon to monarch

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/monarch-ui#49]
There was some discussion about doing this.   Not sure when it happens, but wanted a placeholder for it.  

https://github.com/geneontology/ribbon

**Comment by pnrobinson** [comment]
@monicacecilia is this issue still active?

**Comment by monicacecilia** [comment]
@pnrobinson Not that I am aware of. I have not heard about any plans for implementation in the past 7 months, so I assume - as pointed out by Nathan above - that there is no urgency with this at all.

I am inclined to think that the current UI plans are moving in a different direction and this issue could be tabled for the foreseeable future; that's why it does not have a neither a milestone nor a project attached to it.

**Comment by nathandunn** [comment]
This might be a good @cmungall  question, as well.   

What is currently in the AGR also uses biolink for GO, the same as monarch, but can be used for phenotypes, multi-organism, etc.  It wouldn't be hard to integrate (would probably be @lpalbou doing most of the work).

**Comment by kshefchek** [comment]
per the monarch meeting, this is again of interest

**Comment by mellybelly** [comment]
we talked about identifying the set of upheno upper terms, and possibly color coding them and the table.

**Comment by lpalbou** [comment]
The ribbon has evolved a lot in the last year and most classes in the repo will be deprecated. What is integrated in the alliance and used for both GO/Expression/Disease is in that folder: https://github.com/geneontology/ribbon/tree/master/src/components . And we use a new data model to create & fill the ribbon strips (e.g. [GO Ribbon Summary API](http://api.geneontology.org/api/ontology/ribbon/?subset=goslim_agr&subject=MGI:98214&subject=UniProtKB:P19793&subject=RGD:3610&subject=ZFIN:ZDB-GENE-070314-2&subject=ZFIN:ZDB-GENE-990415-243&subject=FB:FBgn0003964&exclude_IBA=true))

However, I have started working on the web component version, that will follow the same data model. It will be easy to integrate in monarch as it will be a matter of loading the script and setting correctly some attributes.

Do you plan / want to use the ribbon only for go annotations or for other annotations as well ?

**Comment by nathandunn** [comment]
@lpalbou  We had talked briefly with @cmungall about potentially adding phenotypes as well if the API calls will still align.

**Comment by monicacecilia** [comment]
nope. :bowtie:
