### ISSUE TITLE
Update web services documentation

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-ui#499]
(Requested by @mellybelly in Slack on 2022-10-15)

Melissa said, "can someone take charge of updating our web services documentation? https://monarchinitiative.org/about/monarch-web-services".

(Apologies if there's already a ticket for this somewhere! I didn't see one in this repo, but I'm not sure if this is the only place to check.)

**Comment by monicacecilia** [comment]
This has now been resolved, and all documentation for Monarch can be found in two places (by design) at 
1) https://monarch-initiative.github.io/monarch-documentation/
2) https://monarch-initiative.github.io/monarch-ingest/Create-an-Ingest/
