### ISSUE TITLE
Update ontology licensing info

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-ui#500]
(Requested by @mellybelly in Slack on 2022-10-15)

Melissa said, "this also needs updating: https://monarchinitiative.org/about/licensing#ontologies
[7:39](https://monarchinitiative.slack.com/archives/G013K8KQ7BR/p1665844774827799)
i also can't find the monarch OLS mentioned on our site."

(Apologies if there's already a ticket for this somewhere! I didn't see one in this repo, but I'm not sure if this is the only place to check.)

**Comment by nlharris** [comment]
The new site doesn't seem to have a licensing page.

**Comment by nlharris** [comment]
Looks like @kltm just noticed this as well: https://github.com/monarch-initiative/helpdesk/issues/107

**Comment by monicacecilia** [comment]
This is a dupe of https://github.com/monarch-initiative/monarch-app/issues/834
