### ISSUE TITLE
Add instructions for submitting data/knowledge to Monarch

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-ui#501]
From an email discussion in Aug/Sept 2022.

Melissa:
> I noticed our instructions for data submission by individuals are not that clear, so we will work on enhancing that coming up.

Nomi:
> I think it would make sense to create a page about data submission and then we can link to it from https://monarchinitiative.org/help/contact (normally I would not expect so much info on a Contact page, just physical and email address, but since we already have a lot of info there we could add a link to this new page)
> 2. https://monarchinitiative.org/about/monarch
> 
> https://monarchinitiative.org/about/data-sources would actually be the most logical place to add a link, but that appears to be a dynamically generated table, with no static text, so if we wanted to add something to it, it would require a bit more work. That page may be generated from https://github.com/monarch-initiative/monarch-ui/blob/master/src/views/Sources.vue or that may be the old one; I’m not sure whether monarch-ui or monarch-ui-new is the active repo.
> 
> (btw, speaking of out of date documents, i happened upon https://github.com/monarch-initiative/QC/blob/master/docs/about.md
> that should probably be marked obsolete.)

Melissa:
> +1 to all of it!

[see email thread for more discussion]

Chris:
> I think it is good to have some general text on "submitting knowledge to monarch" prominently visible on the site, perhaps with sections like:
> 
> - how to contribute to existing knowledge in Monarch
>      - links to issue trackers for HPO, Mondo, etc
>      - how to make suggestions about changes to annotations
> - how to submit new phenotypic or disease terms
> - how to submit data such as gene-phenotype associations
>      - how to structure your knowledge in kgx
> - how to submit all data for a new organism
>      - process of creating a new ontology in uPheno
>      - how to structure your knowledge in kgx
> - how to submit phenopackets
> 
> I think this satisfies some kind of definition of "data deposition" without falsely advertising an archival function we don't serve
>

**Comment by monicacecilia** [comment]
Closed in favour of https://github.com/monarch-initiative/monarch-app/issues/833
