### ISSUE TITLE
Mastodon account for Monarch

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-ui#503]
Many science-y people are leaving Twitter for Mastodon. Should we set up a Monarch account on Mastodon?
(BTW, I wasn't sure which repo to put this in, please move as appropriate!)
@sagehrke

**Comment by sagehrke** [comment]
@monicacecilia agreed we will make a Mastodon account for Monarch. @sagehrke will lead that initial effort.

**Comment by sagehrke** [comment]
The account is created, and an introduction post is posted. https://genomic.social/@monarch_initiative
