### ISSUE TITLE
YouTube Monarch channel

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-ui#505]
We have an OBO Academy YouTube. Could post other Monarch videos, such as tutorials.
Can we make a Monarch playlist that includes the NIH video? 
(BTW, I wasn't sure which repo to put this in, please move as appropriate!)
@sagehrke

**Comment by sagehrke** [comment]
The link to our channel is here: https://www.youtube.com/channel/UCKAkmAIIfPZc5kjdait-MdQ

**Things to contemplate:**
- [ ] Update the most relevant videos with the new intro and exit slide with Monarch branding.  
   - [ ] Intro to command line part 1 and 2
   - [ ] Pull requests part 1 and 2
   - [ ] How to be an open science ontologist 
- [ ] Create new playlists
- [ ] Add channel description 
- [ ] Update the custom handle to be something relevant to the team
- [ ] Add email address for if people want to contact us

**Comment by nlharris** [comment]
Assigned to @sagehrke at their request

**Comment by sagehrke** [comment]
Monarch now has a distinct YouTube channel that can be found here: https://www.youtube.com/@monarchinitiative 
This will be used for all videos for the Monarch Initiative and all its programs. We will link to OBO Academy YouTube videos as appropriate. 
FYI: @monicacecilia @nlharris @cmungall @pnrobinson @mellybelly @jmcmurry
