### ISSUE TITLE
Change the name of the "Analyze Phenotypes" tool.

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#57]
To better represent the functionality of the tool, this is a suggestion to change the name of the tool from “Analyze Phenotypes” to something such as “Phenotype Profile Search” or “Phenome Search.”

<img width="380" alt="Screen Shot 2019-05-09 at 12 48 25 PM" src="https://user-images.githubusercontent.com/1714621/57599635-3cb40980-750c-11e9-8954-ca42eeaa20e3.png">

**Comment by monicacecilia** [comment]
Another suggestion: Phenotype Profile Match

**Comment by TomConlin** [comment]
Phenotype Explorer
