### ISSUE TITLE
Update Data Sources page, display metadata about load & version.

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#58]
The Monarch website should display information about the current load. That is, we should display metadata about what version of the Monarch data load is currently being used, (also what version of the ontologies) and where the file(s) can be found. 

For an example, see what is done in [AmiGO](http://amigo.geneontology.org/amigo). 

<img width="364" alt="Screen Shot 2019-05-09 at 12 46 59 PM" src="https://user-images.githubusercontent.com/1714621/57599847-e85d5980-750c-11e9-8eb3-cc3d9bd828c1.png">

 * [ ] Include additional metadata in dataset.ttl metadata in dipper load @mbrush 
      - number of associations
      - distinguish source date/version from monarch
      - TBD: void vs datacube? @mbrush 
 * [x] Add route to BioLink @deepakunni3 https://github.com/biolink/biolink-api/pull/286
 * [x] Add page to UI @cmungall

**Comment by cmungall** [comment]
Update - working on this with @justaddcoffee @deepakunni3 @monicacecilia 

Currently requires dev API, e.g.
http://localhost:8081/sources?api=development

Until datasets route is merged into production.

Currently looks like this:

![image](https://user-images.githubusercontent.com/50745/58291783-88b84700-7d73-11e9-82d1-8e7ae37fcbae.png)

@deepakunni3 will extend the cypher template in scigraph to include title and other fields

@justaddcoffee will continue working with @TomConlin on adding summary stats into datasets.ttl files, which we can then store in the UI

@DoctorBud can you tidy up the UI, use a proper table, etc

**Comment by monicacecilia** [comment]
For Sources page: add metadata in additional columns, and hyperlink to the files being described. https://beta.monarchinitiative.org/sources This requires updates in biolink.

**Comment by monicacecilia** [comment]
Also for updates to Sources page, we need to:
- Clarify the version for each file
- Update to a more meaningful name for each file

**Comment by monicacecilia** [comment]
Information that we would like to display about the latest load: 
- The entire database was last loaded on ‘this date.’
- The last release of the Monarch database was done on ‘this date.’

Going to split this ticket to separate 'data load' tasks from 'sources page' tasks.

**Comment by pnrobinson** [comment]
@monicacecilia @jmcmurry @cmungall I do not understand our conversation from yesterday -- we were saying that we do not have any way of getting the last versions of our sources, and yet we seem to have this page -- https://monarchinitiative.org/about/sources
Why can't we simply import that? It looks like a fancy version of the Amigo sources?

**Comment by monicacecilia** [comment]
I think this page is brilliant, and we should have something like it included in our 'About' pages as well. (I must confess that this is the first time I see it). It seems to me like the information in the 'Date Updated' column may have been entered by hand. 

@pnrobinson What I think the comments (and parts of this issue) are asking is a page that includes both information about the latest version, metadata, and links to ttl files, including summary statistics. 

@kshefchek @cmungall - On this side note: I don't know when the exercise to 'make a list of all current pages and decide whether we are going to replicate them in the new site or not' happened, or whether it is tracked somewhere, but it would be very useful to see the results of that, and see if we are keeping track of what has been ported over and what has not yet been created. Do either or you know where I can find information about this?

**Comment by monicacecilia** [comment]
Strategy for updates to Data Sources page: (with @cmungall and @kshefchek)
- Current 'Data Sources' page in legacy monarch-app https://monarchinitiative.org/about/sources
- File can be found here: https://github.com/monarch-initiative/monarch-app/blob/master/conf/resource_data_descriptions.json
- Current path in monarch-ui: monarchinitiative.org/sources
------
To Do:
- [ ] Inject the descriptions from this page into dipper, and use the data in the new 'Sources' page. Add via docstrings and push some of this documentation into the metadata. 
- [ ] Convert the json file to yaml and add it to dipper, keeping the yaml source
- [ ] In the table, the 'Data categories' column will be done using BioLink.
- [ ] Add metadata in additional columns, and hyperlink to the files being described. This requires updates in biolink.

**Comment by monicacecilia** [comment]
@justaddcoffee, @deepakunni3 - ping!

**Comment by justaddcoffee** [comment]
thanks @monicacecilia ! Chatted briefly with @cmungall about this last week, and hope to have a Dipper PR soon that will both firm up our Dipper metadata model and also generate metadata about each source that we can use to populate the monarch-ui sources page. (Obviously this will only happen after the next Monarch data release.)  Also once [this PR](https://github.com/monarch-initiative/dipper/pull/746) is merged, we will have biolink category data/statistics about each Dipper ingest that we can display also (e.g. our OMIM ingest contains xx,000 gene-disease triples, xx,000 publication-disease triples, etc)

**Comment by justaddcoffee** [comment]
https://github.com/monarch-initiative/dipper/pull/809 has just been merged, and should help a lot with this ticket once a data release is made using this code

**Comment by monicacecilia** [comment]
@kshefchek - says we can do a test on beta. Here's your ToDo :bowtie:

**Comment by iimpulse** [comment]
Updates here?

**Comment by kshefchek** [comment]
Nope I haven’t yet updated scigraph, is there something else we can prioritize?

**Comment by justaddcoffee** [comment]
I dove into Biolink.js/Sources.vue a bit, and I think I understand what we need to do. Will discuss with @deepakunni3 how to get the data from the biolink-api.

> Nope I haven’t yet updated scigraph, is there something else we can prioritize?

@kshefchek sorry, you probably mentioned this, but are the metadata (i.e. the dataset ttl) for the data-sources page loaded in Scigraph at this point? Can't remember what you said the status is

**Comment by deepakunni3** [comment]
The metadata has been loaded into scigraph-data-dev and scigraph-data. The dataset/metadata route in BioLink API has been updated to fetch all relevant metadata from SciGraph.

Justin is now working on using this route to display in the UI.

@justaddcoffee Feel free to update as needed.

**Comment by jmcmurry** [comment]
Regarding the styling, I'd like to suggest accordions so that the list of sources is easier to see at a glance.

**Comment by justaddcoffee** [comment]
> Regarding the styling, I'd like to suggest accordions so that the list of sources is easier to see at a glance.

@jmcmurry Have a look at [this PR](#269), slightly better I think

**Comment by justaddcoffee** [comment]
@monicacecilia too

**Comment by justaddcoffee** [comment]
Possibly can close this ticket? @monicacecilia

**Comment by monicacecilia** [comment]
I'll do it with great joy, but first, @justaddcoffee, are we ready to tick off these pending requests?  (from above in the ticket).
To Do:
- [ ] Inject the descriptions from this page into dipper, and use the data in the new 'Sources' page. Add via docstrings and push some of this documentation into the metadata. (@justaddcoffee)
- [ ] Convert the json file to yaml and add it to dipper, keeping the yaml source (@justaddcoffee)

**Comment by justaddcoffee** [comment]
I think we can tick these two boxes. The way it works now is that most metadata is retrieved from Biolink via [Biolink.js](https://github.com/monarch-initiative/monarch-ui/blob/master/src/api/BioLink.js) but some attributes like display name are retrieved from [this static json](https://github.com/monarch-initiative/monarch-ui/blob/master/src/api/StaticSourceData.js) which the 2nd item alludes to. This gives us a way to manually add things not in the metadata, and override/correct data where necessary, since it takes a while for data to get from Dipper to Biolink-api

**Comment by monicacecilia** [comment]
Brilliant! Thanks! :bowtie:

**Comment by monicacecilia** [comment]
Accordions fixed with #269.
Holy mackerel... I think we've done it. :bowtie:
