### ISSUE TITLE
Update the Home page

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#65]
On the home, About Us and About Monarch pages, text needs to be updated. 

On the home page, we need to update information about `The Monarch Initiative` and `What we do`

<img width="700" alt="Screen Shot 2019-05-13 at 12 50 26 PM" src="https://user-images.githubusercontent.com/1714621/57649685-b89a6a00-757d-11e9-862d-2c163726865e.png">

Under the 'About' menu item in the top level menu selection, 'About Monarch' should be updated. 
- [ ] Reduce length: the text is too lengthy and it is difficult to parse what is important
- [ ] Update images to reflect most recent data available

(to be continued...)

**Comment by nicolevasilevsky** [comment]
@jmcmurry did you work on this already?

**Comment by monicacecilia** [comment]
Oh, you are correct, @nicolevasilevsky, @jmcmurry shared with us that she was working on this. I'll remove you from this task. Thank you! 😃

**Comment by monicacecilia** [comment]
@jmcmurry - ping! 😉

**Comment by monicacecilia** [comment]
Intro text on 'home', at http://beta.monarchinitiative.org/
'About Monarch' text at http://beta.monarchinitiative.org/about/monarch/

**Comment by monicacecilia** [comment]
With tips from @kshefchek:
- In the list of collaborators, remove Garvan Institute and add The Jackson Laboratory.
- Check the list of grants supporting Monarch to make sure we have the latest information.

**Comment by monicacecilia** [comment]
(continuation...) 

From @kshefchek in #107 

Pages to be updated:
- [ ] Publications. Previous page on monarch-app (legacy) https://monarchinitiative.org/page/pubs
- [ ] Data sources. Legacy page https://monarchinitiative.org/about/sources
- [ ] Services. Legacy page https://monarchinitiative.org/page/services
- [ ] Link to us. Legacy page https://monarchinitiative.org/page/links
- [ ] Releases. Legacy page https://monarchinitiative.org/page/releases

Some potential overlap with #58

**Comment by monicacecilia** [comment]
Work on additional 'About' pages is progressing at #107

**Comment by iimpulse** [comment]
We might consider re-working this section? I have a few suggestions on the next call. Lets make sure we revist this.

**Comment by pnrobinson** [comment]
@jmcmurry @mellybelly @cmungall @monicacecilia  @dosumis @drseb @julesjacobsen I am trying to be extra critical, but I do not think the opening sentence gets across any useful information, and it sounds awfully cliched.
```
Our philosophy is based on the premise that we want to make all the data count. 
We are driven to truly integrate biological information using semantics, and present 
it in a novel way, leveraging phenotypes to bridge the knowledge gap.
```

How about something along these lines

The Monarch Initiative is an integrative data and analytic platform connecting phenotypes to genotypes across species. The correlation of phenotypic outcomes and disease with genetic variation and environmental factors is a core pursuit in biology and biomedicine. We have created or contribute to many essential bio-ontologies that together enable sophisticated and semantically integrated computational analysis across gene, genotype, variant, disease, and phenotype data. We lead the development of the  <link>Human Phenotype Ontology</link>, which is used across the world for genomic diagnostics in genetic disease and other areas. We have created <link>Mondo</link>, a unified disease ontology that represents the most comprehensive integration of disease entities ever achieved. We are major contributors to the development of genomics standards in the Global Alliance for Genomics and Health. We have developed algorithms and tools that are in use by multiple communities for tasks including the identification of animal models of human disease through phenotypic similarity, phenotype-driven computational support for differential diagnostics, and translational research.

Picture 1--the Washington eye picture. Caption. Find out more about cross specific phenotype analysis. We need to have a separate page that describes this, but to start off with it would be helpful just to provde a list of the major pubmeds such as Washington, uberon, uberpheno, Exomiser

Picture 2--the HPO hierarchy that we have been using in recent presentations. Caption. The Human Phenotype Ontology. Link to HPO page and to most recent NAR2019 article.

Picture 3 -- Phenopackets graphic. Link to the GitHub repo and the read the docs

etc. We should have at least six figures with captions that link to the most interesting resources.

**Comment by monicacecilia** [comment]
@pnrobinson - the text you added is great. I recall hearing once that the text in the page was only a 'place holder' so this is perfect. Question: do you envision all of this information on the Home page or in the 'About' page.

**Comment by monicacecilia** [comment]
Adding details here from Melissa's email and Peter's comments in other tickets.

From @mellybelly's wishlist: 
- [ ] Look, feel, and behavior should be consistent with that of the HPO website. 
- [ ] Check that all links between the Monarch and HPO website are working correctly.
- [ ] The ontology navigation should either work similarly to that of HPO and/or we could repurpose the OLS in some way. Too many ways is confusing to users. Noted at #123 

From @pnrobinson: 
- [ ] Reduce the size of the Twitter widget column. In progress at #122

**Comment by monicacecilia** [comment]
Dear @nicolevasilevsky - I've just sent you a brief message about kindly requesting your help on this issue once again. Thank you!

**Comment by monicacecilia** [comment]
## Collection of tasks for updating the monarch-ui home page

@iimpulse, the following are tasks for updating the current Home page. All text and graphs below can be found on the Monarch shared drive, here, and I also sent them via email to you directly. 

### 1. Update top level menus as shown here, creating place pages where necessary. Note changes highlighted with yellow: please replace the word 'Citing' with the word 'Cite.'  
- [ ] Task has been completed.

![Screen Shot 2019-07-12 at 4 31 34 PM](https://user-images.githubusercontent.com/1714621/61163406-9d3ad500-a4c2-11e9-9d2b-7bfbc8822498.png)

------

### 2. Remove the crossed off content as shown below
- [ ] Task has been completed.

![Screen Shot 2019-07-12 at 4 30 26 PM](https://user-images.githubusercontent.com/1714621/61163381-78def880-a4c2-11e9-8559-075b076c4d67.png)

-------

### 3. Update content in home page by replacing the text as shown below. 
The text for this is as follows: 
- Title: ```Connecting phenotypes to genotypes across species```
- Body of text: <code> The Monarch Initiative is an integrative data and analytic platform connecting phenotypes to genotypes across species, bridging basic and applied research with semantics-based analysis. The correlation of phenotypic outcomes and disease with genetic variation and environmental factors is a core pursuit in biology and biomedicine. </code>
- [ ] Task has been completed. 

![Screen Shot 2019-07-12 at 4 34 15 PM](https://user-images.githubusercontent.com/1714621/61163469-03275c80-a4c3-11e9-88ce-442d7dafe8b2.png)

 -------

### 4. Add a figure and legend to the page as shown below. 
- Figure legend: Title in bold: ```The phenotype annotation coverage of human coding genes.```  Legend: <code>The figure shows the availability of curated phenotypes that have been attributed to human genes (direct or inferred via orthology) across a range of model organisms (blue circle). Phenotypes for human genes curated in humans are shown in orange, and they only represent 20% of the total number of genes in the human genome. Data from more species raises the phenotypic coverage of human coding genes to 82%.</code>
- [ ] Task has been completed. 

![Screen Shot 2019-07-12 at 4 38 33 PM](https://user-images.githubusercontent.com/1714621/61163628-0838db80-a4c4-11e9-9970-bf3b5197250a.png)

-------

### 5. Reduce the size of the columns for Twitter widget and News widget, to something similar as shown below. The objective is to ultimately reduce both the width of the widget block, and with it the size of the font inside the widget (especially for Twitter). 
- [ ] Task has been completed.

![Screen Shot 2019-07-12 at 4 45 09 PM](https://user-images.githubusercontent.com/1714621/61163696-a5940f80-a4c4-11e9-8488-9152f07732c1.png)

-------

### 6. Update the logos of our participating institutions: 
- The logo from the Garvan Institute needs to be removed. 
- The logo for Jackson Lab should be added.
- The logo from Berkeley lab should go up next to JAX
- Reorganize the remaining logos as shown below.
- [ ] Task has been completed.

![Screen Shot 2019-07-12 at 4 55 34 PM](https://user-images.githubusercontent.com/1714621/61163885-f9ebbf00-a4c5-11e9-8281-d9bc520c232f.png)

**Comment by monicacecilia** [comment]
@pnrobinson, all, 
- I broke this ticket in two. This ticket keeps all info related to 'Home page.' 
- I created a new ticket to update the 'About Monarch' page at #135. 
- Other updates are listed in #107.

**Comment by iimpulse** [comment]
Lets move 4 and 2 into the about page and roll with what we got for now, we can take a swing through static content at a later point in time.

**Comment by nicolevasilevsky** [comment]
@monicacecilia would you still like my help with this?

**Comment by monicacecilia** [comment]
@iimpulse - These comments came in after you merged the PR, but please have a look at https://github.com/monarch-initiative/monarch-ui/pull/136 for fixes. Thank you!

**Comment by iimpulse** [comment]
Can we close?
