### ISSUE TITLE
Phenogrid takes too long to load

### ISSUE THREAD

**Issue by dnahotline** [monarch-initiative/monarch-ui#66]
https://monarchinitiative.org/page/phenogrid
I'm on Safari, was exploring Monarch, and wanted to see what phenogrid would do. Never loaded. 
<img width="265" alt="Screenshot 2019-05-13 14 49 43" src="https://user-images.githubusercontent.com/23179382/57656903-9b21cc00-758e-11e9-9b59-8fce939db2d9.png">

**Comment by cmungall** [comment]
Looks like an issue with the old prod site

We should be testing https://beta.monarchinitiative.org/

**Comment by monicacecilia** [comment]
@DoctorBud - in the beta site, where can we find a page or a tool that emulates the behaviour of what https://monarchinitiative.org/page/phenogrid used to do? Or how do we get to a display of information in the form of a Phenogrid?

**Comment by kshefchek** [comment]
It looks like the version of phenogrid we depend on for the production site has beta.monarch hardcoded into the config, but we've replaced beta with the new SPA app.  Can we do some nginx tinkering or hot patch the code on production?

**Comment by kshefchek** [comment]
This was fixed with the nginx changes applied via https://github.com/monarch-initiative/monarch-ui/issues/91
