### ISSUE TITLE
Correct the term of the disease to Fanconi anemia (not Fanconi's anemia)

### ISSUE THREAD

**Issue by dnahotline** [monarch-initiative/monarch-ui#69]
<img width="1108" alt="Screenshot 2019-05-13 15 42 01" src="https://user-images.githubusercontent.com/23179382/57659059-d1167e80-7595-11e9-8241-5a8c71dda59a.png">

**Comment by kshefchek** [comment]
This is an issue with our highlighting code (in ontobio), we are prioritizing a synonym over a primary label.  Will fix in ontobio and test on the app.

**Comment by kshefchek** [comment]
@dnahotline if you test it on https://alpha.monarchinitiative.org/?api=development it should be fixed, please reopen if any other results look wrong.
