### ISSUE TITLE
Update news items on home page

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-ui#72]
Replace the current items under News and Events with the latest blog posts.
Relates to #73

**Comment by DoctorBud** [comment]
I think @nicolevasilevsky did this already with https://github.com/monarch-initiative/monarch-ui/pull/82

Please confirm and close this issue.

**Comment by nicolevasilevsky** [comment]
yes, please close (looks like I can only comment, not close)

**Comment by nlharris** [comment]
Glad that the live site finally has updated news items! Thanks, @kshefchek!
