### ISSUE TITLE
genome features should get pulled from ensembl

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/monarch-ui#79]
- genome features data should get pulled from ensembl

- We are already getting the Ensembl data via mygene.info calls . . . . for human, but we can do that everywhere:

https://mygene.info/v3/query?q=HGNC:3603&fields=summary,genomic_pos,name,symbol,taxid&species=all

returns:
    
```
{
  "max_score": 12.227615,
  "took": 4,
  "total": 1,
  "hits": [
    {
      "_id": "2200",
      "_score": 12.227615,
      "genomic_pos": {
        "chr": "15",
        "end": 48645849,
        "ensemblgene": "ENSG00000166147",
        "start": 48408306,
        "strand": -1
      },
      "name": "fibrillin 1",
      "summary": "This gene encodes a member of the fibrillin family of proteins. The encoded preproprotein is proteolytically processed to generate two proteins including the extracellular matrix component fibrillin-1 and the protein hormone asprosin. Fibrillin-1 is an extracellular matrix glycoprotein that serves as a structural component of calcium-binding microfibrils. These microfibrils provide force-bearing structural support in elastic and nonelastic connective tissue throughout the body. Asprosin, secreted by white adipose tissue, has been shown to regulate glucose homeostasis. Mutations in this gene are associated with Marfan syndrome and the related MASS phenotype, as well as ectopia lentis syndrome, Weill-Marchesani syndrome, Shprintzen-Goldberg syndrome and neonatal progeroid syndrome. [provided by RefSeq, Apr 2016].",
      "symbol": "FBN1",
      "taxid": 9606
    }
  ]
}
```

The follow-up call is:  https://rest.ensembl.org/documentation/info/lookup

and we use this:  https://rest.ensembl.org/lookup/id/ENSG00000157764?content-type=application/json;expand=1

otherwise we have to provide a sequence and range, but this is better

**Comment by nathandunn** [comment]
From @cmdcolin . . this would be the range query API: https://rest.ensembl.org/documentation/info/overlap_region

**Comment by nathandunn** [comment]
I think this API will work, but I think the problem is that gene data for non-human is largely pulled from the MOD sources, which are not necessarily aligned with Ensembl (and I know in some cases they are not by design as in the case with ZFIN).

**Comment by monicacecilia** [comment]
@nathandunn - so what happened, then? Was there a decision not to do this?

**Comment by nathandunn** [comment]
If folks want to do this that’s fine.  At some point jbrowse will work with Ensembl.

I wouldn’t do this unless Dipper is pulling from the same version as Ensembl.   Currently Ensembl is often behind the mods (which is my understanding of where data is coming from for dipper).
