### ISSUE TITLE
need to fix google structured data 

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/monarch-ui#83]
#78 is not yet fixed.   

Let's fix #81 first to make it easier to test. 

See: https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Fbeta.monarchinitiative.org%2Fgene%2FZFIN%3AZDB-GENE-001103-2

The JSONLD script is there, but its not getting picked up.  Possible because its a JSON Array. 

The snippet provided is actually fine:

```
[
  {
    "@context": "http://schema.org",
    "@type": "Organization",
    "url": "https://monarchinitiative.org",
    "email": "info@monarchinitiative.org"
  },
  {
    "@context": "http://schema.org",
    "@type": "WebSite",
    "url": "https://monarchinitiative.org",
    "potentialAction": {
      "@type": "SearchAction",
      "target": "https://monarchiniative.org/search/{term}",
      "query-input": "required name=term"
    }
  }
]
```

Note @cmungall  / @kltm  . . I think just adding it with a simple tag doesn't quite work.  

Not sure what secret sauce that google structured data needs from vuejs, or maybe google is just grumpy today.  

Not high priority, so can recheck later.

**Comment by monicacecilia** [comment]
Hi @nathandunn, should failed attempts from #78 and #81 close this ticket, then?

**Comment by nathandunn** [comment]
No, they are fine.  This should still go in, I just don't know if its high priority for @cmungall  or not and it would probably go on @kshefchek 's plate at this point anyway.

**Comment by monicacecilia** [comment]
Thanks. I don't think it is high priority for first release, but something to keep in the radar.
