### ISSUE TITLE
URI problem in search box at new monarch-ui

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-ui#84]
In some cases, when typing a term into the 'Search' box of the beta version of the new monarch-ui, a problem with URIs is evident. For example, try doing a search with the beginning of a gene name, in the example, I used the word 'hox.' See the errors in suggested lines 3 and 7 in the screenshot below:
 
<img width="700" alt="Screen Shot 2019-05-09 at 12 45 03 PM" src="https://user-images.githubusercontent.com/1714621/57600092-a84aa680-750d-11e9-9b31-7d39907dcec0.png">

**Comment by monicacecilia** [comment]
Still work in progress --> From SciGraph/golr-loader#45: we still get IRIs in the equivalent curie field when an IRI does not resolve, see [monarch-initiative/monarch-ui#63 (comment)](https://github.com/monarch-initiative/monarch-ui/issues/63#issuecomment-500631585)

**Comment by kshefchek** [comment]
@monicacecilia can we close this as a dupe of https://github.com/monarch-initiative/monarch-ui/issues/63?

**Comment by monicacecilia** [comment]
Ok. I added #63 to the New UI Project. 

I continue to work on helping us do a better job about documenting progress.
