### ISSUE TITLE
Accommodate search by curie / accession

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui#85]
Breaking out search-by-curie (had been part of https://github.com/monarch-initiative/monarch-app/issues/1383) as a separate ticket as it is a long-running and circumscribable issue.

| search issue | query | Top result must be | results must include | status |
| --- | --- | --- | --- | --- |
| **curie** | [HP:0000452](https://beta.monarchinitiative.org/search/HP:0000452) | HP:0000452 |  | Improve ranking |
| **fuzzy curie** | [HPO:0000452](https://beta.monarchinitiative.org/search/HPO:0000452) | HP:0000452 |  | Improve ranking |
| **curie** | [ncbigene:6622](https://beta.monarchinitiative.org/search/ncbigene%3A6622) | ncbigene:6622 |  | Improve ranking |
| **fuzzy curie** | [gene:6622](https://beta.monarchinitiative.org/search/gene%3A6622) | ncbigene:6622 |  | Improve ranking |

The pseudocode would be:
````
if search string contains ':' or '_' 
     check the prefixes in curie_map.yml (note that this check will require case insensitivity)
           if prefix exists, check if there's a corresponding web page for it.
                   if the curie has a corresponding web page in our site, redirect there (skip search results page)
                        else if no corresponding web page exists in our site, go to a generic warning page with the text "The accession number you have searched for does not have a corresponding page in our website, or you may have used a prefix syntax we do not recognize. The prefixes we use are browsable at ...curie_map.yml"
else if search string does not contain ':' or '_' proceed with search as usual.
````

This logic could be baked into solr itself or could be handled client side. It is pretty easy, so defer to your preference as devs.

**Comment by kshefchek** [comment]
The test cases in https://github.com/monarch-initiative/monarch-ui/issues/85#issue-445637420 work well on http://beta.monarchinitiative.org/
