### ISSUE TITLE
interaction tab gives BioLink error

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-ui#93]
E.g

http://beta.monarchinitiative.org/gene/HGNC:17158#interaction

![image](https://user-images.githubusercontent.com/50745/59242858-26a87000-8bc2-11e9-8e80-ec30baec4c43.png)

**Comment by kshefchek** [comment]
failing call: https://api-dev.monarchinitiative.org/api/bioentity/gene/HGNC:17158/interactions?fetch_objects=true&start=0&rows=25

**Comment by deepakunni3** [comment]
I have a fix for this as part of the latest PR: https://github.com/biolink/biolink-api/pull/293

Let me know if you want me to have this fix separately from the PR

**Comment by kshefchek** [comment]
This looks fixed after merging biolink/biolink-api#293
