### ISSUE TITLE
ortholog-phenotype tab should give indication of source/species on main table

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-ui#94]
E.g.
http://beta.monarchinitiative.org/gene/HGNC:17158#ortholog-phenotype

You can get an indication of species when you click on the evidence/provenance thingy but it would be good to have in the main table

I believe blapi should be returning the taxon ID along with the the orthologous gene? Even if as a first pass we just take the ID space (WB, FB, MGI) and show that explicitly that would be awesome

**Comment by kshefchek** [comment]
here is the biolink call, looks like species is incuded, https://api-dev.monarchinitiative.org/api/bioentity/gene/HGNC:17158/ortholog/phenotypes?fetch_objects=true&start=0&rows=25

**Comment by pnrobinson** [comment]
@monicacecilia Do we want to add a new column to the table that will show the species? Should we show the common species name and make it a URL to the NCBI taxon site? If this is the case then I think this would be a good JAX issue.

**Comment by monicacecilia** [comment]
Yes, let's show species information on the table as well. A good ticket for JAX. I'm assigning to you guys and you can distribute / assign internally as appropriate.

**Comment by cmungall** [comment]
Not sure why this was closed

https://beta.monarchinitiative.org/gene/HGNC:10848#homolog

![image](https://user-images.githubusercontent.com/50745/63279502-f59d8900-c25d-11e9-9187-916fdfd99b1f.png)

Says human for all, even ZFIN etc

**Comment by kshefchek** [comment]
The ticket was for adding species to the ortholog-phenotype tab, which was added with  https://github.com/monarch-initiative/monarch-ui/pull/157 but it looks like there is a bug on the homolog tab, we should we showing the taxon of the object in the association

**Comment by iimpulse** [comment]
Can someone clarify when we want to show object vs subject on a per tab basis?

Homolog - Subject
Ortholog* - Object?

**Comment by kshefchek** [comment]
https://github.com/monarch-initiative/monarch-app/tree/master/conf/golr-views/single-tab under result_weights is what we have configured on legacy:

> grep -P '(subject|object)_taxon\^' *

I think in the majority of cases, we want to show the subject taxon (if we're showing it at all).  For the homolog table we want to show the object taxon.

**Comment by cmungall** [comment]
ah yes feel free to make a new ticket

**Comment by iimpulse** [comment]
This should be okay to close now yeah?
