### ISSUE TITLE
Minor improvements for term pages

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-ui#96]
Some can be slow to load. Would be good to diagnose so we can come up with a plan, e.g.

http://beta.monarchinitiative.org/phenotype/HP:0010831

(this may have been a temporary issue, but it would be good to get an idea of load time of different pages under different loads)

We calculate both `|association|` and `|gene|`, but we show in different places (former once you click on the tab, latter on the tab itself) which can look a bit odd? I'm not sure, get a second opinion on this.
http://beta.monarchinitiative.org/phenotype/HP:0010831#gene

![image](https://user-images.githubusercontent.com/50745/59243257-d8946c00-8bc3-11e9-96ec-2c21e0237654.png)

**Comment by kshefchek** [comment]
I think both of these issues (performance, counts) come from upstream components - solr, ontobio, biolink.  I think it makes sense to get rid of distinct counts in favor of globally using association counts.  The exception being special stats endpoints where we only was unique counts of entities of type <T>.  Long standing ticket - https://github.com/monarch-initiative/monarch-app/issues/1263

I think the action item here is to move and task over in biolink.

**Comment by monicacecilia** [comment]
@deepakunni3 - hi :bowtie: 
This may be another issue to pick up at biolink. May I kindly ask you to please have a look and update as necessary when you get the chace? Thank you!

**Comment by jmcmurry** [comment]
In latest PR by @iimpulse responsiveness seems to be better in my hands. Still could improve, but thought I would mention.

**Comment by monicacecilia** [comment]
I don't know if @deepakunni3 has had a chance to look a the 'counts' issue yet. 
I don't have the powers to transfer this issue to the [BioLink repo](https://github.com/biolink/biolink-api/) from here, so I created a new ticket there. 
Closing here in favour of [this ticket on the biolink/biolink-api repo](https://github.com/biolink/biolink-api/issues/308).

**Comment by monicacecilia** [comment]
Also added https://github.com/biolink/biolink-api/issues/308 to [New UI v1.0 Project Board](https://github.com/orgs/monarch-initiative/projects/8).
